In [ ]:
#dataset = pd.read_csv('mnist_test.csv')

In [12]:
import numpy as np
import pandas as pd

qtInter,qtOut,qtInput,e,alpha,epoca = 100,10,784,0,0.1,0
dataset = pd.read_csv('mnist_train.csv')
v = np.random.randn(qtInput, qtInter) / np.sqrt(qtInput)
w = np.random.randn(qtInter, qtOut) / np.sqrt(qtInter)
ativacao = 'sig'

In [13]:
grafico = np.array([[0]*2])

In [14]:
def trataLinha(inp):
    retorno = np.array(inp)
    return retorno/255

def targetVetor(labels, num_classes=10):
    retTarget = np.eye(num_classes)[labels]
    return retTarget

def inputZ(inp):
    inX = np.zeros(qtInter)
    for j in range (qtInter):
        inX[j] = np.sum(inp * np.array(v[:,j]))
    return inX

def inputY(inp,pesos):
    inX = np.zeros(qtOut)
    for k in range (qtOut):
        inX[k] = np.sum(inp * np.array(pesos[:,k]))
    return inX

def deltainJ (dK,peso):
    inJ = np.zeros(qtInter)
    for j in range (qtInter):
        for k in range (qtOut):
            inJ[j] += dK[k] * peso[j][k]
    return inJ

def funcAtivacao(x,func) :
    if (func == 'relu') : 
        return np.maximum(x,0) 
    elif (func == 'sig') : 
        return (1/(1+np.exp(-x)))
    elif (func == 'tanh'):
        return np.tanh(x)

def derivada(x,func):        
    if (func == 'relu') : 
        return (0 if x<0 else 1)
    elif (func == 'sig') : 
        return (x * (1 - x))
    elif (func == 'tanh') :
        return (1 - np.power(x,2))

def verificaAcerto(tar,out):
    indTar = np.unravel_index(np.argmax(tar, axis=None), tar.shape)
    indOut = np.unravel_index(np.argmax(out, axis=None), out.shape)
    if (indTar == indOut):
        return True
    else :
        return False

def deltaK(targetK,Yk,YinK,func) :
    dK = np.zeros(qtOut)
    for i in range (qtOut) :
        erro = targetK[i] - Yk[i]
        deriv = derivada(YinK[i],func)
        dK[i] = erro * deriv
    return dK

def deltaJ(inJ,inZ,func):
    delJ = np.zeros(qtInter)
    for j in range (qtInter):
        deriv = derivada(inZ[j],func)
        delJ[j] = inJ[j] * deriv
    return delJ

def deltaW(dK,Ze):
    dW = np.empty_like(w)
    for j in range(qtInter):
        for k in range(qtOut):
            dW[j][k] = alpha * dK[k] * Ze[j]
    return dW

def deltaV(linha,dJ):
    dV = np.empty_like(v)
    for i in range(qtInput):
        for j in range (qtInter):
            dV[i][j] = alpha * dJ[j] * linha[i]
    return dV

In [15]:
def algoritmo(isTreino,qtEpoca):
    global epoca
    for i in range (qtEpoca):
        readLine(dataset,isTreino)
        epoca+=1

In [16]:
def readLine(dSet,isTreino):
    global e
    r,e = 1,0
    for row in dSet.itertuples(index=False):
        linha = list(row)
        target = targetVetor(linha.pop(0))
        linha = trataLinha(linha)
        forward(linha,isTreino,target,r)
        r+=1
        
def forward(linha,isTreino,target,r):
    global e
    global grafico
    inZ = inputZ(linha)
    Z = funcAtivacao(inZ,ativacao)
    inY = inputY(Z,w)
    Y = funcAtivacao(inY,ativacao)
    if (not verificaAcerto(target,Y)):
        e+=1
    if isTreino:
        backPropagation(inZ,Z,inY,Y,target,linha)
    a = 100 - ((e/r)*100)
    if (r!=0 and r%20 == 0):
        print (target)
        print (Y)
        print (f'Linha: {r} Epoca: {epoca} Erros: {e}  Acerto: {a} %' + '\n' + '_________' )
        grafico = np.append(grafico,[[r,a]],axis=0)
    
def backPropagation(inZ,Z,inY,Y,target,linha):
    delK,inJ,delJ =[],[],[]
    delK = deltaK(target,Y,Y,ativacao) 
    inJ  = deltainJ(delK,w)
    delJ = deltaJ(inJ,Z,ativacao)
    atualizaPesos(delK,Z,linha,delJ)

In [17]:
def atualizaPesos(delK,Z,linha,delJ):
    global w
    global v
    correcaoW = deltaW(delK,Z)
    correcaoV = deltaV(linha,delJ)
    w = corrigePeso(w,correcaoW)
    v = corrigePeso(v,correcaoV)
    
def corrigePeso(peso,delta):
    return np.add(peso,delta)

In [18]:
algoritmo(True,1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.12503863 0.19014754 0.15969324 0.16802285 0.13715877 0.1415232
 0.1679147  0.1508822  0.15187222 0.1270293 ]
Linha: 20 Epoca: 0 Erros: 18  Acerto: 10.0 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0.14297028 0.11743854 0.11973602 0.12385375 0.10187773 0.09431482
 0.13955014 0.12008569 0.09504524 0.12510165]
Linha: 40 Epoca: 0 Erros: 37  Acerto: 7.5 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.11200474 0.09104548 0.07141331 0.1338226  0.11723651 0.08220207
 0.08943723 0.11088211 0.11663326 0.19439539]
Linha: 60 Epoca: 0 Erros: 55  Acerto: 8.333333333333343 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.17317513 0.22628022 0.064851   0.08352986 0.09572983 0.07410799
 0.10574546 0.0918858  0.08375537 0.09839708]
Linha: 80 Epoca: 0 Erros: 71  Acerto: 11.25 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.14111973 0.11903696 0.062756   0.1059612  0.11910206 0.06706999
 0.12126222 0.14458757 0.1120531  0.10012664]
Linha: 100 Epoca: 0 Erros: 88  Acerto: 12.0

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0.20774557 0.06107726 0.04906652 0.13590044 0.05700254 0.12502938
 0.13676034 0.17642968 0.20428999 0.14436917]
Linha: 800 Epoca: 0 Erros: 541  Acerto: 32.375 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.09103996 0.04691168 0.08797102 0.08154339 0.08968683 0.09838621
 0.0903823  0.3700121  0.11099074 0.22178545]
Linha: 820 Epoca: 0 Erros: 550  Acerto: 32.92682926829268 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.03435212 0.19107632 0.07086438 0.04985239 0.10179083 0.11774255
 0.06188818 0.43401082 0.10727261 0.21785842]
Linha: 840 Epoca: 0 Erros: 560  Acerto: 33.33333333333334 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.57087752 0.01649045 0.08759637 0.14573952 0.23301592 0.16177524
 0.12739292 0.11754226 0.0660525  0.06920069]
Linha: 860 Epoca: 0 Erros: 569  Acerto: 33.837209302325576 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0.06535874 0.13241073 0.1246958  0.20365079 0.19142427 0.06946464
 0.10252554 0.089717   0.10919507 0.07667011]
Linha

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.0056295  0.73859256 0.27614591 0.11666269 0.05875359 0.09951971
 0.03164523 0.08472311 0.0975187  0.0780357 ]
Linha: 1580 Epoca: 0 Erros: 837  Acerto: 47.0253164556962 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.09429794 0.03945944 0.05775702 0.587484   0.02462365 0.17999567
 0.02084808 0.07571743 0.13242663 0.11039642]
Linha: 1600 Epoca: 0 Erros: 844  Acerto: 47.25 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.06578155 0.01954599 0.02002065 0.04996948 0.07708412 0.06863113
 0.01484901 0.80452303 0.03774047 0.38912121]
Linha: 1620 Epoca: 0 Erros: 850  Acerto: 47.53086419753087 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.02585229 0.03379958 0.0220963  0.06557228 0.07843614 0.06675544
 0.01131811 0.70959692 0.04520134 0.32446779]
Linha: 1640 Epoca: 0 Erros: 856  Acerto: 47.80487804878049 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.01057113 0.04492986 0.02611373 0.04196135 0.22935351 0.08073028
 0.04748373 0.21981281 0.10741605 0.43657019]
Linh

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.01159793 0.15964712 0.33954126 0.27501077 0.0441422  0.13022382
 0.00297573 0.01951056 0.25110173 0.02867881]
Linha: 2340 Epoca: 0 Erros: 1008  Acerto: 56.92307692307692 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.01317951 0.06106584 0.64185719 0.43046117 0.13589103 0.06902932
 0.01022896 0.00451993 0.23309367 0.01116713]
Linha: 2360 Epoca: 0 Erros: 1012  Acerto: 57.11864406779661 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.01135124 0.28565681 0.18598163 0.10085383 0.02565944 0.04539762
 0.00598115 0.07785734 0.22486539 0.08644657]
Linha: 2380 Epoca: 0 Erros: 1018  Acerto: 57.226890756302524 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.01891699 0.01676331 0.88296915 0.05196225 0.06417183 0.02620584
 0.08768969 0.00301238 0.43730295 0.01222833]
Linha: 2400 Epoca: 0 Erros: 1019  Acerto: 57.54166666666667 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.0035364  0.37424019 0.2371325  0.04284762 0.16856705 0.07721427
 0.00639502 0.019556   0.3940862

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.00615988 0.01826693 0.0066611  0.00653413 0.22174046 0.06738586
 0.04942227 0.08860459 0.16108229 0.62625325]
Linha: 3100 Epoca: 0 Erros: 1147  Acerto: 63.0 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.0159067  0.09151805 0.15970569 0.40770566 0.0125971  0.06503801
 0.01651038 0.01476083 0.17409979 0.00904596]
Linha: 3120 Epoca: 0 Erros: 1150  Acerto: 63.141025641025635 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0.01584035 0.00316154 0.06040788 0.00143118 0.13448017 0.07948344
 0.88785586 0.02305339 0.01747694 0.12688555]
Linha: 3140 Epoca: 0 Erros: 1153  Acerto: 63.28025477707007 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.02832024 0.01295571 0.07113793 0.77835073 0.0092377  0.14487203
 0.00826526 0.01356473 0.34178388 0.02005406]
Linha: 3160 Epoca: 0 Erros: 1155  Acerto: 63.449367088607595 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.00679806 0.02371314 0.96335419 0.04806674 0.02903452 0.00886487
 0.11350755 0.01313113 0.08239756 0.0070726 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0.21050772 0.00181893 0.00340469 0.09806883 0.00303279 0.56204723
 0.03178792 0.00518983 0.09768985 0.03609193]
Linha: 3840 Epoca: 0 Erros: 1254  Acerto: 67.34375 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0.08397591 0.00346203 0.00301028 0.20092304 0.00338074 0.55272777
 0.02856032 0.01731274 0.07349082 0.05169768]
Linha: 3860 Epoca: 0 Erros: 1255  Acerto: 67.48704663212436 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.07005298 0.00603253 0.10519774 0.01954492 0.00365952 0.28818438
 0.01440918 0.00244182 0.79091982 0.0201644 ]
Linha: 3880 Epoca: 0 Erros: 1256  Acerto: 67.62886597938144 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0.01525482 0.01266483 0.00496715 0.00919992 0.01197535 0.04524872
 0.00176379 0.94222061 0.03127089 0.24935197]
Linha: 3900 Epoca: 0 Erros: 1256  Acerto: 67.7948717948718 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0.00453118 0.01634842 0.06987805 0.00138279 0.07210687 0.07012151
 0.96551735 0.00247545 0.03849352 0.0763263

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.72622983e-03 4.75045968e-02 5.30423157e-02 4.82808617e-02
 2.37568666e-03 4.41227976e-03 3.86524232e-04 9.32232215e-01
 2.10436185e-02 8.96680481e-02]
Linha: 4560 Epoca: 0 Erros: 1345  Acerto: 70.50438596491227 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[5.85834350e-02 3.37589689e-03 1.75234464e-02 7.80178908e-01
 7.56489399e-04 3.10008570e-01 9.11026933e-03 9.03620868e-03
 2.64003518e-02 3.26313217e-03]
Linha: 4580 Epoca: 0 Erros: 1347  Acerto: 70.58951965065502 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.04751666 0.00117595 0.97352812 0.0238506  0.0103576  0.00222325
 0.06207945 0.00177748 0.04920669 0.0033567 ]
Linha: 4600 Epoca: 0 Erros: 1349  Acerto: 70.67391304347825 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0.00130956 0.27358197 0.00487024 0.00077478 0.67266617 0.09994747
 0.05922872 0.01913601 0.00719277 0.09725901]
Linha: 4620 Epoca: 0 Erros: 1350  Acerto: 70.77922077922078 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[5.61173630e-04 7.

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.67466942e-02 9.11022569e-04 7.97819948e-01 4.77060154e-03
 4.26682790e-02 1.61129459e-02 6.59678017e-02 9.61792236e-05
 3.21058975e-01 2.70095197e-02]
Linha: 5260 Epoca: 0 Erros: 1435  Acerto: 72.71863117870723 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.95299019e-02 2.48963390e-03 8.22699602e-02 1.22061110e-04
 2.71873792e-02 3.06340403e-02 9.83043879e-01 4.27779997e-04
 4.02922286e-03 2.80450795e-02]
Linha: 5280 Epoca: 0 Erros: 1435  Acerto: 72.82196969696969 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.02207134 0.01911351 0.01580068 0.05095179 0.00185988 0.2126029
 0.00146679 0.01706007 0.76494198 0.02205642]
Linha: 5300 Epoca: 0 Erros: 1437  Acerto: 72.88679245283019 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.87464436e-01 2.21005418e-04 6.33374483e-03 1.68267664e-02
 1.76856520e-04 4.53791118e-02 7.59072759e-04 6.13781343e-02
 5.24088054e-03 6.04045939e-03]
Linha: 5320 Epoca: 0 Erros: 1444  Acerto: 72.85714285714286 %
_________
[0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.43649099e-01 3.16308212e-04 2.96216646e-04 2.07471941e-03
 4.86021538e-02 2.27626787e-02 1.14599540e-03 8.70389760e-01
 2.11829980e-03 1.64444207e-01]
Linha: 5960 Epoca: 0 Erros: 1523  Acerto: 74.44630872483222 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.15355875e-03 1.69743617e-03 4.57224813e-04 1.23104627e-01
 3.31888631e-02 1.02971566e-01 5.10665670e-03 1.00748031e-01
 7.08043688e-02 7.53235941e-01]
Linha: 5980 Epoca: 0 Erros: 1527  Acerto: 74.4648829431438 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[4.80726984e-03 9.09942073e-04 7.98083905e-04 1.14500905e-02
 3.42509329e-02 3.44584459e-02 8.97536333e-03 1.86953743e-01
 3.31029029e-02 9.27704926e-01]
Linha: 6000 Epoca: 0 Erros: 1527  Acerto: 74.55 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[3.40869214e-03 1.39642754e-03 8.08076583e-04 4.07439795e-03
 1.41009069e-01 1.83187464e-01 9.47644928e-03 5.19507770e-02
 1.02983893e-01 8.74867798e-01]
Linha: 6020 Epoca: 0 Erros: 1527  Acerto: 74.63455149

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.78849058e-01 5.86120535e-05 4.19823949e-03 2.47902167e-03
 7.93533146e-04 6.17106241e-02 1.53450696e-02 1.97081625e-03
 1.07478520e-02 8.20778492e-04]
Linha: 6620 Epoca: 0 Erros: 1581  Acerto: 76.1178247734139 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.14914985e-03 1.24417783e-02 9.94115388e-01 4.09237453e-02
 2.67527593e-03 3.66163285e-04 1.33169597e-02 1.23386847e-03
 1.00732162e-01 1.24875576e-03]
Linha: 6640 Epoca: 0 Erros: 1582  Acerto: 76.17469879518072 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.00341661 0.02227421 0.00922674 0.03253673 0.00813361 0.16646631
 0.00394622 0.00203505 0.79869129 0.02118208]
Linha: 6660 Epoca: 0 Erros: 1585  Acerto: 76.2012012012012 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.00070055 0.02277402 0.00374744 0.00352299 0.08075505 0.01527127
 0.00635263 0.08618962 0.03961318 0.55251004]
Linha: 6680 Epoca: 0 Erros: 1587  Acerto: 76.24251497005989 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.00194256 0.024728

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.05722156e-03 2.75085818e-02 3.40181105e-02 5.29514688e-04
 8.97341368e-01 3.78474134e-02 1.13090169e-01 1.96887745e-02
 2.74493892e-02 1.84114667e-02]
Linha: 7320 Epoca: 0 Erros: 1676  Acerto: 77.10382513661202 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0.02677164 0.0038013  0.00414756 0.75169522 0.00453079 0.22888544
 0.01410084 0.00997226 0.00467273 0.00365493]
Linha: 7340 Epoca: 0 Erros: 1678  Acerto: 77.13896457765668 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.00371548 0.18010059 0.10756811 0.00565222 0.00385601 0.09169628
 0.0530463  0.00091229 0.7481233  0.00655242]
Linha: 7360 Epoca: 0 Erros: 1681  Acerto: 77.16032608695652 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.18363458e-02 1.34340831e-03 3.54044888e-02 1.78728985e-04
 4.85671627e-03 3.68233983e-02 8.99927341e-01 1.83722062e-04
 6.62786639e-02 6.20804538e-02]
Linha: 7380 Epoca: 0 Erros: 1683  Acerto: 77.1951219512195 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[3.13342946e-04 4.3

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[3.40146980e-03 1.09518160e-04 4.08325711e-03 3.34855939e-04
 9.06120408e-01 8.16476722e-03 3.07774141e-02 1.46338855e-02
 1.02859079e-02 7.42315707e-03]
Linha: 8000 Epoca: 0 Erros: 1762  Acerto: 77.975 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[8.88444464e-01 1.30052040e-04 7.51151911e-04 1.39987891e-03
 2.70520771e-04 3.35840514e-02 1.41109190e-02 2.31534608e-02
 1.34503039e-03 5.06246621e-04]
Linha: 8020 Epoca: 0 Erros: 1765  Acerto: 77.9925187032419 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.32062909e-03 3.35733343e-03 8.80914288e-02 8.99319440e-01
 3.04736002e-03 1.27872863e-02 3.24568594e-04 1.62987175e-03
 5.81324504e-02 1.96335945e-02]
Linha: 8040 Epoca: 0 Erros: 1768  Acerto: 78.00995024875621 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[7.86092616e-03 2.46762160e-04 5.19565557e-04 1.60759345e-03
 1.19730301e-01 9.10051991e-03 1.22042960e-02 4.49035003e-03
 1.72947764e-01 9.14382184e-01]
Linha: 8060 Epoca: 0 Erros: 1768  Acerto: 78.0645161

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.00206449 0.09455842 0.00158404 0.00226793 0.00110193 0.61777961
 0.01595442 0.00093185 0.90778808 0.01407719]
Linha: 8660 Epoca: 0 Erros: 1837  Acerto: 78.78752886836028 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[4.28380451e-04 9.71810142e-01 6.00720273e-02 6.90678330e-03
 6.26142252e-04 1.54419028e-02 3.33958858e-03 2.07416630e-03
 9.27221877e-02 2.45465024e-03]
Linha: 8680 Epoca: 0 Erros: 1840  Acerto: 78.80184331797236 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.53021775e-02 5.08285706e-04 5.84600611e-05 2.78583541e-03
 1.05267464e-02 1.74495843e-02 5.78529002e-04 9.07352579e-01
 1.80301178e-03 2.01804420e-01]
Linha: 8700 Epoca: 0 Erros: 1844  Acerto: 78.80459770114942 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[7.69393597e-03 5.29677403e-03 1.80367027e-02 7.88785402e-05
 3.65406696e-02 3.00502931e-02 1.91083233e-01 8.19947686e-04
 7.36283211e-02 9.32805369e-03]
Linha: 8720 Epoca: 0 Erros: 1850  Acerto: 78.78440366972477 %
_________
[1. 0. 0.

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[8.46761042e-03 1.54934446e-03 2.05264334e-02 9.98518060e-01
 7.03225155e-04 6.88377444e-02 1.65504990e-04 1.14821594e-03
 6.36552571e-03 7.36176894e-04]
Linha: 9320 Epoca: 0 Erros: 1920  Acerto: 79.39914163090128 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[3.87130791e-02 3.62956079e-04 7.65544633e-03 3.41066925e-03
 1.24166169e-01 8.92578729e-01 6.80045114e-02 1.95920649e-03
 6.45263595e-03 1.14089253e-03]
Linha: 9340 Epoca: 0 Erros: 1921  Acerto: 79.43254817987152 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[5.56150079e-04 6.56960743e-03 1.47571471e-02 3.50212850e-02
 4.34867794e-03 7.62683238e-02 5.00920019e-02 4.14143648e-04
 6.79139111e-01 3.90287708e-03]
Linha: 9360 Epoca: 0 Erros: 1924  Acerto: 79.44444444444444 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.62217016e-02 7.36527283e-05 5.47998640e-02 1.03168961e-04
 5.51643499e-03 1.40000091e-01 9.57743510e-01 2.66418338e-04
 1.46246064e-03 1.94311288e-04]
Linha: 9380 Epoca: 0 Erros: 1928  Acerto

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.00090163 0.00202222 0.01559426 0.02013741 0.31780265 0.00134095
 0.00768375 0.00104285 0.00625997 0.47820765]
Linha: 9980 Epoca: 0 Erros: 1987  Acerto: 80.09018036072145 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.32706245e-02 1.18634513e-03 1.81138055e-03 1.65208372e-03
 2.60460597e-03 1.80108633e-02 6.34089770e-04 9.08492821e-01
 4.42921551e-03 1.25333898e-01]
Linha: 10000 Epoca: 0 Erros: 1987  Acerto: 80.13 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.23524541e-02 2.64398197e-04 1.25222257e-03 8.26313849e-04
 2.90754934e-03 2.30828026e-02 1.06087901e-03 7.01908105e-01
 1.50417088e-02 5.52351079e-01]
Linha: 10020 Epoca: 0 Erros: 1988  Acerto: 80.15968063872256 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.67465647e-02 6.03282567e-04 9.51941242e-05 2.75912568e-03
 1.95503510e-02 8.07332200e-02 1.68666353e-04 9.86581042e-01
 2.36351804e-03 2.96617018e-02]
Linha: 10040 Epoca: 0 Erros: 1993  Acerto: 80.14940239043824 %
_________
[0. 0. 0. 0. 0. 0.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.09384989e-03 1.71750855e-04 1.82696931e-03 1.80858742e-05
 5.97578168e-01 8.97664955e-02 2.84379122e-02 8.38157001e-03
 6.38894409e-02 4.76173700e-02]
Linha: 10640 Epoca: 0 Erros: 2044  Acerto: 80.78947368421052 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.65864176e-04 9.23155258e-01 3.77038813e-02 7.10335518e-02
 2.97376038e-04 3.40553684e-03 4.61343571e-03 1.57628956e-02
 1.53721140e-02 1.41300736e-02]
Linha: 10660 Epoca: 0 Erros: 2045  Acerto: 80.81613508442777 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[3.86618148e-04 6.71967685e-04 1.24972026e-04 3.48592799e-04
 8.27865881e-01 1.92209656e-01 4.87064500e-03 1.11497020e-02
 6.40517145e-02 1.53683281e-01]
Linha: 10680 Epoca: 0 Erros: 2047  Acerto: 80.83333333333333 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.93648421e-03 2.12652581e-03 9.29749232e-01 3.61348341e-03
 2.77235307e-03 5.76011707e-04 1.68337396e-02 3.19684403e-04
 3.98710785e-02 6.66181666e-03]
Linha: 10700 Epoca: 0 Erros: 2048  Ac

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.85592549e-04 8.44474740e-01 1.13947251e-01 3.78729937e-02
 2.14662913e-03 1.02148798e-02 2.15567799e-03 4.10841409e-04
 1.22885355e-01 2.57671946e-03]
Linha: 11280 Epoca: 0 Erros: 2097  Acerto: 81.40957446808511 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.60951162e-03 6.26628151e-04 9.64171008e-01 3.17806582e-02
 6.19970930e-05 9.34476746e-04 1.36846730e-02 1.51018711e-01
 2.26390837e-03 9.11279258e-04]
Linha: 11300 Epoca: 0 Erros: 2100  Acerto: 81.41592920353982 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[5.52766144e-03 7.18228398e-04 9.60982699e-01 1.35993450e-03
 1.46811436e-01 8.37011694e-04 8.36123721e-02 1.60408675e-05
 6.99784548e-03 6.46366329e-04]
Linha: 11320 Epoca: 0 Erros: 2100  Acerto: 81.44876325088339 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[9.40766459e-04 1.68010703e-02 6.94948561e-01 1.10944341e-02
 1.17935211e-02 1.84266183e-04 1.80786417e-02 8.24526112e-04
 2.37099982e-03 9.61797503e-02]
Linha: 11340 Epoca: 0 Erros: 2101  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[7.81635045e-03 1.82607442e-04 3.71293326e-05 7.52116222e-04
 3.00154579e-03 2.18937360e-02 2.66139542e-04 9.62059622e-01
 1.19728287e-02 2.53005876e-01]
Linha: 11920 Epoca: 0 Erros: 2171  Acerto: 81.78691275167785 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[4.20357102e-04 8.85061872e-01 2.57755433e-02 7.57626722e-02
 2.14566437e-04 1.06312954e-02 8.79059786e-03 2.38860280e-03
 2.81765330e-02 5.73617561e-03]
Linha: 11940 Epoca: 0 Erros: 2173  Acerto: 81.80067001675042 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.79736505e-03 3.39912112e-03 2.31219402e-02 9.34391109e-04
 2.41364945e-03 1.81080285e-02 9.92476676e-01 2.97244176e-04
 6.97087643e-03 4.67307641e-03]
Linha: 11960 Epoca: 0 Erros: 2174  Acerto: 81.8227424749164 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[8.94243859e-03 1.90603751e-03 2.01596254e-01 6.85347356e-01
 8.15605552e-05 1.73361048e-02 2.91267140e-05 8.33476352e-03
 1.78037973e-01 1.75427521e-04]
Linha: 11980 Epoca: 0 Erros: 2175  Ace

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.28360330e-02 2.86684916e-02 3.23824881e-02 2.16387053e-02
 8.74584411e-05 8.53934293e-02 3.13131359e-03 4.26758665e-04
 6.55572009e-01 8.02412325e-04]
Linha: 12560 Epoca: 0 Erros: 2248  Acerto: 82.10191082802548 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.98266076e-03 7.84965750e-04 7.38491502e-03 8.37431344e-04
 9.89903996e-04 3.00312037e-02 2.75967399e-05 9.92965284e-01
 3.40432931e-03 2.20704571e-02]
Linha: 12580 Epoca: 0 Erros: 2250  Acerto: 82.11446740858506 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[8.80742756e-04 2.65395628e-03 1.72694277e-02 2.91964257e-03
 5.33352201e-04 3.90669748e-03 1.78287187e-05 9.94513050e-01
 1.90138881e-03 3.42785795e-02]
Linha: 12600 Epoca: 0 Erros: 2254  Acerto: 82.11111111111111 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.60143666e-03 1.96523547e-03 1.60155688e-02 3.72218667e-03
 9.97388278e-03 6.43795263e-02 1.02924820e-03 5.21729581e-05
 9.82513415e-01 4.42665996e-03]
Linha: 12620 Epoca: 0 Erros: 2257  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[6.34154349e-03 4.66645156e-04 8.21569364e-03 2.06679720e-03
 5.42130686e-04 3.67387350e-03 3.35900239e-05 9.96140249e-01
 2.39832428e-03 2.90135941e-02]
Linha: 13200 Epoca: 0 Erros: 2340  Acerto: 82.27272727272728 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[6.19550621e-03 7.28018832e-04 9.30572639e-03 1.43892739e-02
 6.11005662e-04 2.57008566e-02 2.49895529e-03 1.26138290e-04
 9.90472462e-01 4.51956792e-02]
Linha: 13220 Epoca: 0 Erros: 2340  Acerto: 82.29954614220877 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.44165046e-04 2.58918885e-02 1.82032757e-01 8.81158757e-01
 1.38644233e-03 2.72808741e-02 4.21814192e-04 4.86239549e-04
 1.63826275e-02 1.80621168e-03]
Linha: 13240 Epoca: 0 Erros: 2340  Acerto: 82.3262839879154 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.10917812e-01 1.66937965e-02 1.43826508e-02 1.70093878e-02
 1.51125190e-03 2.60918408e-01 1.52760445e-02 3.97833389e-05
 6.91911942e-02 1.39384159e-02]
Linha: 13260 Epoca: 0 Erros: 2342  Ace

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.56972102e-02 5.08870253e-04 3.25179942e-02 8.24920558e-01
 1.07319409e-04 1.42407169e-02 6.64324429e-05 3.45007971e-03
 2.73246362e-02 3.30007852e-05]
Linha: 13840 Epoca: 0 Erros: 2394  Acerto: 82.70231213872833 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.46934374e-02 9.70425040e-04 6.59391990e-03 9.32772256e-01
 1.08620300e-02 2.25897018e-02 8.13522681e-04 3.73467403e-04
 8.62307091e-03 1.02659126e-04]
Linha: 13860 Epoca: 0 Erros: 2395  Acerto: 82.72005772005772 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.52766556e-02 1.42113357e-03 1.94927152e-03 9.55393309e-01
 1.86713340e-03 4.99221731e-02 2.88059371e-04 8.94143678e-03
 9.10299130e-03 3.90015290e-05]
Linha: 13880 Epoca: 0 Erros: 2399  Acerto: 82.71613832853026 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.52877708e-02 7.01465386e-04 4.01216259e-03 1.25524230e-03
 1.82842111e-03 8.96146998e-02 6.32952392e-03 1.18261000e-04
 9.38252521e-01 4.31186314e-02]
Linha: 13900 Epoca: 0 Erros: 2400  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.66107581e-03 8.13091955e-05 1.75331409e-04 9.72351360e-05
 2.48185053e-01 4.91495271e-02 4.47769359e-03 2.78935273e-02
 3.06523470e-03 4.71806724e-01]
Linha: 14480 Epoca: 0 Erros: 2479  Acerto: 82.87983425414365 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.03283676e-03 3.82330639e-03 1.78899510e-02 7.72244458e-04
 2.71406826e-03 2.02354970e-02 7.80153303e-03 2.12982683e-04
 9.89681689e-01 6.44846555e-03]
Linha: 14500 Epoca: 0 Erros: 2480  Acerto: 82.89655172413794 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.74136773e-04 8.39099957e-04 2.76449895e-02 2.07176023e-02
 1.10489041e-03 4.69690212e-04 5.96516422e-05 9.82470407e-01
 6.55674698e-04 2.39756980e-02]
Linha: 14520 Epoca: 0 Erros: 2483  Acerto: 82.89944903581267 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.37971791e-02 4.05571914e-05 1.26828051e-03 5.00555112e-04
 9.58722278e-01 3.63961200e-02 2.04637718e-02 5.20256782e-03
 1.08832607e-03 6.47421654e-02]
Linha: 14540 Epoca: 0 Erros: 2485  Ac

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.75881526e-01 2.71124343e-05 5.68758277e-03 9.66615227e-03
 3.88292424e-05 2.60513390e-02 5.80286175e-04 2.81749109e-02
 2.06669743e-04 1.03048266e-04]
Linha: 15120 Epoca: 0 Erros: 2555  Acerto: 83.10185185185185 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.15823496e-02 1.23461036e-03 1.46323917e-02 9.87320796e-01
 4.01937935e-03 9.25196411e-02 1.28306921e-04 2.77000514e-04
 8.09519540e-04 4.08940256e-05]
Linha: 15140 Epoca: 0 Erros: 2556  Acerto: 83.11756935270806 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[5.91714249e-03 1.15351477e-04 1.31666243e-02 8.55039236e-06
 2.38412021e-02 6.86319172e-03 9.53571518e-01 2.04453113e-03
 3.00884345e-04 1.66732715e-02]
Linha: 15160 Epoca: 0 Erros: 2557  Acerto: 83.13324538258576 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[5.09823674e-04 3.42764103e-04 2.17432587e-03 1.47626373e-05
 9.12901304e-01 7.78080300e-04 2.75194763e-02 1.65611383e-02
 1.81276861e-03 2.51213044e-01]
Linha: 15180 Epoca: 0 Erros: 2562  Ac

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[8.87412487e-01 9.60368503e-06 1.07030904e-01 7.97698010e-03
 1.06708526e-05 4.77923255e-03 5.89717299e-02 2.09482006e-03
 1.28843639e-03 2.52380779e-03]
Linha: 15760 Epoca: 0 Erros: 2616  Acerto: 83.40101522842639 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7.43044970e-02 1.27805426e-04 1.83383360e-03 8.70777225e-06
 2.95309543e-01 2.06475110e-04 1.47543963e-02 9.68204927e-02
 1.59751723e-03 3.99961864e-02]
Linha: 15780 Epoca: 0 Erros: 2620  Acerto: 83.39670468948036 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.35757845e-03 9.32834663e-05 9.76852664e-01 8.26389102e-03
 3.39551925e-03 4.47659650e-04 1.68067282e-02 4.24558810e-05
 7.97337900e-02 3.20770961e-03]
Linha: 15800 Epoca: 0 Erros: 2621  Acerto: 83.4113924050633 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[2.16070120e-02 2.43594679e-04 3.80603519e-04 1.19170409e-01
 5.68285105e-04 9.71355777e-01 1.29335016e-02 8.82707115e-04
 9.27935526e-04 7.52673922e-03]
Linha: 15820 Epoca: 0 Erros: 2622  Ace

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.26855665e-04 4.64948749e-02 1.26779153e-03 2.29095967e-04
 8.70793037e-01 6.58443432e-02 1.40913295e-02 1.19615311e-03
 1.99500554e-02 1.19624139e-02]
Linha: 16400 Epoca: 0 Erros: 2679  Acerto: 83.66463414634146 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.28621349e-03 1.87261274e-03 2.44258236e-05 3.36810665e-04
 2.99797296e-02 2.09422229e-02 1.08723970e-04 9.48910363e-01
 5.72189067e-03 7.47377047e-02]
Linha: 16420 Epoca: 0 Erros: 2680  Acerto: 83.67844092570036 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.77080510e-01 5.11935537e-05 1.04686394e-03 2.88875188e-02
 1.39621198e-05 1.20446348e-02 2.62550349e-05 7.95623824e-02
 8.28126500e-04 5.27538463e-04]
Linha: 16440 Epoca: 0 Erros: 2681  Acerto: 83.69221411192214 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[8.88151056e-04 2.16316671e-04 9.34002695e-05 1.61804629e-04
 9.88143214e-01 2.55551736e-01 4.49926735e-03 1.35480254e-03
 9.72727860e-03 6.23361885e-02]
Linha: 16460 Epoca: 0 Erros: 2685  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[2.65092513e-02 1.08745122e-04 4.86457370e-03 3.59133696e-06
 7.23039249e-01 2.96137636e-02 3.89468009e-01 1.25387760e-02
 6.13860837e-04 2.91288770e-03]
Linha: 17040 Epoca: 0 Erros: 2751  Acerto: 83.8556338028169 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[6.01365225e-04 4.60702135e-02 4.46569345e-02 1.79040236e-04
 1.70080526e-03 3.37079022e-02 8.83692883e-01 1.57001161e-05
 2.38725212e-01 1.77363493e-03]
Linha: 17060 Epoca: 0 Erros: 2754  Acerto: 83.8569753810082 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.96035435e-01 4.75657936e-05 1.13791871e-01 1.39127899e-05
 2.29187397e-03 6.10233197e-02 2.16457377e-01 1.28511548e-04
 1.00351614e-02 5.04410872e-04]
Linha: 17080 Epoca: 0 Erros: 2754  Acerto: 83.87587822014052 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5.78557663e-03 2.50262215e-02 4.62620181e-02 2.22355018e-03
 6.66279327e-04 8.58319314e-01 1.29010220e-03 2.45442919e-02
 6.19652159e-02 1.82521570e-05]
Linha: 17100 Epoca: 0 Erros: 2756  Acer

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[6.96693948e-03 2.73889363e-04 8.48175658e-03 6.21585522e-05
 4.04067831e-02 3.74643210e-03 2.45476812e-02 1.26262874e-03
 1.44911828e-01 2.74509178e-02]
Linha: 17680 Epoca: 0 Erros: 2819  Acerto: 84.0554298642534 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.03660452e-02 7.95737080e-04 5.43829224e-03 5.00648890e-01
 1.09976305e-04 1.26462108e-01 1.54779177e-03 3.07072349e-04
 4.33418132e-02 2.66472221e-04]
Linha: 17700 Epoca: 0 Erros: 2822  Acerto: 84.05649717514125 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[8.78888521e-04 2.89286143e-04 9.22326264e-03 2.65693663e-01
 3.37027387e-04 3.70251510e-04 1.50438322e-04 9.34963311e-01
 4.97039026e-04 5.08195132e-02]
Linha: 17720 Epoca: 0 Erros: 2826  Acerto: 84.05191873589165 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[8.35850187e-01 6.18272744e-03 1.87638619e-04 1.91059408e-03
 4.79470202e-04 1.88876260e-01 1.47088022e-02 2.25327421e-03
 2.34353411e-02 1.60204078e-03]
Linha: 17740 Epoca: 0 Erros: 2827  Ace

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.28839742e-01 3.02096899e-06 6.91743721e-03 3.53624422e-03
 1.30758224e-04 2.81910588e-02 3.48818791e-02 1.05493344e-03
 6.44073262e-03 1.32653712e-03]
Linha: 18320 Epoca: 0 Erros: 2873  Acerto: 84.31768558951966 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.12095825e-05 9.88155351e-01 1.52275318e-02 9.77232687e-03
 2.73203144e-04 3.93101589e-03 7.54690144e-03 5.79019400e-03
 7.59480556e-03 6.78151638e-03]
Linha: 18340 Epoca: 0 Erros: 2876  Acerto: 84.31842966194111 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.28727998e-05 9.88912859e-01 5.98645075e-02 7.55138680e-03
 7.34079597e-04 4.17640902e-03 1.05830677e-02 1.56535567e-03
 4.47938439e-03 1.74626228e-03]
Linha: 18360 Epoca: 0 Erros: 2878  Acerto: 84.32461873638344 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[3.29994938e-02 1.89328906e-04 7.00795722e-04 1.05887655e-03
 1.51210006e-03 9.92489366e-01 2.61700609e-04 9.07949521e-03
 9.33534885e-02 1.85441682e-03]
Linha: 18380 Epoca: 0 Erros: 2878  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.66939194e-03 4.84507678e-05 7.74886127e-05 7.26054643e-04
 4.86032450e-03 1.25045419e-02 8.05292205e-04 1.19201392e-01
 8.01039711e-03 9.43183343e-01]
Linha: 18960 Epoca: 0 Erros: 2919  Acerto: 84.60443037974684 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.96534627e-03 5.03459559e-05 9.34021169e-03 7.65018834e-03
 2.77275244e-05 7.49028914e-04 1.23949593e-05 9.99234932e-01
 2.07447371e-04 3.31756137e-02]
Linha: 18980 Epoca: 0 Erros: 2921  Acerto: 84.61011591148578 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.48303102e-03 3.42942676e-05 2.40195911e-04 1.79994235e-04
 8.78336834e-01 1.70806124e-01 6.47776664e-03 1.42673061e-03
 1.89418810e-02 4.44737959e-02]
Linha: 19000 Epoca: 0 Erros: 2922  Acerto: 84.62105263157895 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.62925052e-01 4.81031173e-05 1.80204383e-03 5.13451017e-01
 7.75412193e-06 4.96185340e-01 4.40750756e-04 3.16334480e-03
 4.24388588e-03 2.36763184e-04]
Linha: 19020 Epoca: 0 Erros: 2925  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.22170754e-03 1.10295742e-05 1.48851743e-03 3.44895493e-06
 7.65485109e-01 7.78715707e-04 8.92312073e-03 3.81121071e-02
 4.41975150e-02 1.48446911e-01]
Linha: 19600 Epoca: 0 Erros: 2975  Acerto: 84.82142857142857 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.48636812e-03 8.09653922e-05 4.70336456e-04 5.56360926e-05
 6.10480481e-02 3.82845885e-03 1.36351790e-02 5.64742228e-03
 5.11527291e-02 8.90653047e-01]
Linha: 19620 Epoca: 0 Erros: 2976  Acerto: 84.83180428134557 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.36780207e-04 9.02259186e-01 2.14779932e-02 7.55916878e-03
 2.51138236e-04 2.23802840e-03 1.30491758e-03 1.93627054e-03
 2.48974780e-01 2.21989756e-03]
Linha: 19640 Epoca: 0 Erros: 2977  Acerto: 84.84215885947047 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[2.53643909e-02 3.49157931e-05 1.14965415e-04 8.08291643e-03
 7.64051877e-04 9.92377220e-01 1.45539482e-03 5.95128643e-05
 4.00703371e-02 9.94847381e-03]
Linha: 19660 Epoca: 0 Erros: 2978  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[7.19829624e-05 1.96442764e-03 7.26101187e-01 8.51111451e-05
 1.28292739e-03 5.06795087e-05 5.74944291e-03 1.96748564e-02
 1.45631800e-02 2.21769649e-02]
Linha: 20240 Epoca: 0 Erros: 3025  Acerto: 85.05434782608695 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.34466648e-03 1.92399115e-03 1.44595983e-03 9.87078489e-01
 5.04535747e-03 1.16106837e-02 3.88821933e-05 1.01418650e-04
 3.02112803e-02 5.44522517e-03]
Linha: 20260 Epoca: 0 Erros: 3026  Acerto: 85.06416584402764 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[7.46481873e-05 9.43329290e-01 4.65864989e-02 7.33020291e-03
 2.12631216e-04 2.92528355e-03 1.01373393e-02 3.96279105e-04
 2.07578037e-02 1.70539074e-03]
Linha: 20280 Epoca: 0 Erros: 3026  Acerto: 85.07889546351085 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.57597124e-02 4.37023315e-05 9.79659676e-01 8.01278475e-04
 6.52609962e-02 1.11420870e-04 1.48118912e-02 1.87578909e-05
 2.75316182e-03 3.93832204e-03]
Linha: 20300 Epoca: 0 Erros: 3026  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[4.38999670e-05 1.12079454e-03 3.00530427e-05 3.54600547e-03
 9.36584132e-03 1.45305538e-03 3.93310842e-04 4.45104198e-02
 4.41041784e-02 9.86323110e-01]
Linha: 20880 Epoca: 0 Erros: 3069  Acerto: 85.30172413793103 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.06710421e-04 9.09892215e-01 1.97229774e-02 7.55604802e-03
 8.91821344e-04 3.91491948e-03 1.67338475e-02 1.65272687e-04
 2.08753609e-01 1.36613472e-03]
Linha: 20900 Epoca: 0 Erros: 3071  Acerto: 85.30622009569377 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.04304961e-03 1.89552770e-03 4.93181522e-02 9.03758094e-03
 1.66445116e-02 4.14117279e-04 1.60313536e-03 4.43027407e-05
 7.60932862e-01 3.64908989e-03]
Linha: 20920 Epoca: 0 Erros: 3074  Acerto: 85.30592734225621 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.45632545e-01 1.30946816e-04 5.81360672e-01 8.28553299e-02
 7.49250161e-06 4.87056220e-04 6.35185572e-03 1.27746830e-03
 2.14517888e-03 2.02661233e-05]
Linha: 20940 Epoca: 0 Erros: 3077  Ac

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[7.55938967e-03 3.96557818e-05 4.08791345e-04 2.58992463e-02
 8.26957086e-03 9.91247128e-01 1.86015515e-03 8.48590662e-06
 4.51277259e-02 7.08584517e-04]
Linha: 21520 Epoca: 0 Erros: 3123  Acerto: 85.48791821561338 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[5.19286055e-04 7.68930359e-03 8.86566541e-03 9.45208186e-01
 9.55916411e-03 4.77519572e-02 3.21844392e-04 3.79455246e-05
 8.73379333e-02 5.85420034e-03]
Linha: 21540 Epoca: 0 Erros: 3124  Acerto: 85.49675023212627 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.47359765e-03 2.14669503e-03 4.04249838e-03 9.82376258e-01
 1.29156063e-04 2.23745388e-01 4.76859004e-04 8.20373175e-04
 2.65334709e-03 1.39751555e-04]
Linha: 21560 Epoca: 0 Erros: 3125  Acerto: 85.50556586270872 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.87582585e-03 3.86355605e-03 8.32830079e-03 9.51455808e-01
 1.77283972e-03 5.51207306e-02 3.06790705e-04 1.56058249e-03
 6.96735793e-03 5.25868118e-05]
Linha: 21580 Epoca: 0 Erros: 3127  Ac

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.32022356e-01 1.38457862e-05 1.44885817e-01 1.36070117e-02
 4.24596832e-06 1.44273592e-02 7.95953516e-04 6.61884554e-04
 1.61123376e-03 1.33280943e-05]
Linha: 22160 Epoca: 0 Erros: 3170  Acerto: 85.69494584837545 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[8.76579290e-07 9.93236642e-01 8.07946221e-03 7.42249706e-02
 4.39976178e-04 3.37089289e-03 3.40434266e-03 4.75178636e-03
 3.89434235e-03 1.45465867e-02]
Linha: 22180 Epoca: 0 Erros: 3172  Acerto: 85.69882777276825 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[6.79003160e-02 3.00341483e-05 5.24480119e-01 2.66770567e-01
 1.25886534e-03 3.47439267e-02 1.21649789e-03 1.10164166e-04
 9.96048004e-03 1.87872589e-05]
Linha: 22200 Epoca: 0 Erros: 3173  Acerto: 85.7072072072072 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[8.95832354e-03 6.58809431e-04 5.52368194e-02 9.39976173e-01
 2.73285178e-06 1.71979021e-02 1.79359425e-03 8.41369376e-04
 4.80490280e-04 5.93483857e-05]
Linha: 22220 Epoca: 0 Erros: 3178  Ace

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[5.40089506e-04 5.19490234e-05 3.23825101e-04 5.71968701e-05
 6.55701416e-01 1.15857479e-03 1.02574362e-02 8.92685179e-03
 1.27127042e-02 1.74282779e-01]
Linha: 22800 Epoca: 0 Erros: 3245  Acerto: 85.76754385964912 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[8.24532359e-03 1.04580602e-03 1.86365742e-02 3.63013807e-05
 4.24069848e-03 9.92780027e-01 1.46442039e-02 6.76855901e-03
 1.27789141e-02 1.13604360e-06]
Linha: 22820 Epoca: 0 Erros: 3247  Acerto: 85.7712532865907 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.65985615e-04 1.27236559e-05 1.64483705e-03 1.57634170e-05
 8.99320859e-01 8.40254656e-04 2.87507056e-02 8.86358250e-04
 6.08200611e-02 1.17244481e-01]
Linha: 22840 Epoca: 0 Erros: 3250  Acerto: 85.77057793345008 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.53258117e-05 5.15652403e-01 2.05762699e-02 1.56280691e-02
 4.03512670e-04 1.81331781e-03 1.84928718e-03 2.28221830e-03
 4.50802611e-01 1.22150131e-03]
Linha: 22860 Epoca: 0 Erros: 3250  Ace

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[9.25675215e-03 1.79183224e-04 2.28159098e-03 9.95488236e-01
 7.89216859e-06 2.27412651e-02 3.03668950e-04 4.79670573e-04
 1.58850246e-02 2.16154449e-04]
Linha: 23440 Epoca: 0 Erros: 3290  Acerto: 85.96416382252559 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[7.08948846e-05 2.92864357e-04 7.04647619e-04 3.51937652e-03
 9.64299190e-01 2.76259783e-03 4.43615861e-03 1.25068793e-03
 2.97644109e-03 1.64313342e-01]
Linha: 23460 Epoca: 0 Erros: 3292  Acerto: 85.96760443307758 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.59292030e-04 5.26427589e-04 8.20336926e-03 6.31288425e-03
 9.55174676e-05 7.96775324e-04 3.59943464e-06 9.98874818e-01
 3.08616310e-04 4.04086121e-03]
Linha: 23480 Epoca: 0 Erros: 3295  Acerto: 85.96678023850085 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.94879744e-01 3.59079627e-06 2.74109619e-02 1.22814111e-02
 9.63544216e-07 4.27945909e-03 3.54638416e-04 2.41644775e-03
 1.10280613e-03 9.72222607e-06]
Linha: 23500 Epoca: 0 Erros: 3298  Ac

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.14834798e-04 3.98002654e-03 1.04149219e-02 1.05576159e-03
 1.35319048e-03 2.41981676e-02 9.93502835e-01 2.44763483e-06
 2.67395368e-02 2.19637511e-03]
Linha: 24080 Epoca: 0 Erros: 3351  Acerto: 86.08388704318936 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.27904669e-04 2.86607771e-01 6.76687505e-02 9.03335352e-01
 6.21687281e-06 1.45592627e-02 5.47038883e-05 1.98700646e-03
 6.24755884e-03 3.95707510e-04]
Linha: 24100 Epoca: 0 Erros: 3352  Acerto: 86.09128630705393 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[4.48768657e-03 3.54331580e-05 4.62424138e-02 8.43831848e-01
 2.60279648e-05 7.32269223e-03 3.47664194e-04 1.99622326e-02
 1.24048159e-03 1.86575973e-03]
Linha: 24120 Epoca: 0 Erros: 3354  Acerto: 86.09452736318408 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.63700930e-06 9.93479185e-01 1.62371324e-02 1.79126238e-02
 8.98330157e-05 2.06564161e-03 7.38360495e-03 1.18366815e-03
 1.70418878e-02 5.44373389e-03]
Linha: 24140 Epoca: 0 Erros: 3354  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.57669205e-04 3.19856023e-04 1.18357854e-04 1.58405391e-04
 2.40560636e-01 4.18251120e-03 6.16769154e-04 2.16496672e-02
 1.02466586e-01 6.33550671e-01]
Linha: 24720 Epoca: 0 Erros: 3413  Acerto: 86.19336569579288 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.16034402e-04 5.18183594e-03 4.26556799e-02 1.03228811e-03
 2.11695818e-03 2.32044609e-02 9.70002924e-01 1.20918767e-05
 1.19281417e-02 5.26923900e-04]
Linha: 24740 Epoca: 0 Erros: 3415  Acerto: 86.19644300727566 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[3.94407116e-05 5.57685288e-03 2.70812812e-05 1.48107289e-01
 2.59612381e-01 6.00254200e-03 5.63226707e-04 1.51531870e-03
 8.14508658e-03 8.59599136e-01]
Linha: 24760 Epoca: 0 Erros: 3417  Acerto: 86.19951534733441 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[4.42667810e-04 5.95129227e-02 2.90481164e-01 8.26586152e-04
 2.29897398e-04 7.61539846e-03 8.69354331e-01 1.28518321e-05
 1.62034711e-02 2.48150345e-04]
Linha: 24780 Epoca: 0 Erros: 3419  Ac

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5.41450445e-02 5.71531332e-06 5.72830022e-05 3.52737056e-01
 7.63976353e-05 4.09630033e-01 5.19129030e-05 7.18095514e-03
 8.63353580e-03 1.24567300e-03]
Linha: 25360 Epoca: 0 Erros: 3470  Acerto: 86.31703470031546 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.72232917e-02 6.97827296e-06 4.75997181e-03 9.00488003e-04
 1.22502032e-03 8.60317712e-02 3.89798409e-03 2.63789964e-05
 9.77191968e-01 6.22995437e-03]
Linha: 25380 Epoca: 0 Erros: 3470  Acerto: 86.327817178881 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.94075838e-01 4.42005432e-07 1.95803568e-02 4.44159457e-04
 1.54964224e-05 4.05303324e-02 1.08804151e-03 1.22537866e-03
 6.67079136e-03 2.05936809e-04]
Linha: 25400 Epoca: 0 Erros: 3472  Acerto: 86.33070866141732 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.97391078e-05 1.49686770e-04 9.19455096e-04 2.56478275e-06
 9.50375067e-01 2.20739796e-03 4.06089573e-03 8.47662718e-03
 1.87904782e-02 6.92917554e-02]
Linha: 25420 Epoca: 0 Erros: 3472  Acer

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[2.35645614e-04 1.59796366e-04 1.64042307e-02 3.05018050e-05
 5.37030362e-03 1.13474761e-03 9.94538566e-01 4.01075375e-06
 2.09548413e-02 5.82640836e-03]
Linha: 26000 Epoca: 0 Erros: 3511  Acerto: 86.49615384615385 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[5.52529225e-03 1.84331431e-05 1.77816881e-02 2.99601206e-05
 3.66350618e-03 8.18984558e-04 9.83515348e-01 2.16786066e-06
 1.32969923e-01 7.84536971e-04]
Linha: 26020 Epoca: 0 Erros: 3512  Acerto: 86.50269023827825 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.62717205e-03 5.52860884e-05 1.59565306e-02 3.89785341e-05
 2.23598015e-03 8.63795889e-03 9.90438112e-01 2.92262496e-06
 1.10600320e-02 1.90882343e-03]
Linha: 26040 Epoca: 0 Erros: 3512  Acerto: 86.51305683563749 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.93354172e-06 9.32854137e-01 1.29839451e-02 4.72519231e-02
 1.01319936e-04 1.62823702e-03 7.60861981e-04 7.47699042e-03
 3.83058462e-02 9.04322211e-03]
Linha: 26060 Epoca: 0 Erros: 3514  Ac

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.12766597e-01 1.15950515e-05 7.48209429e-03 3.00383050e-04
 3.09746098e-05 3.74420339e-01 2.41621273e-03 1.59335585e-04
 7.76011952e-04 3.35837577e-05]
Linha: 26640 Epoca: 0 Erros: 3559  Acerto: 86.6403903903904 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[5.21923023e-03 4.02411113e-06 1.13894614e-04 3.03577369e-04
 4.43882481e-04 5.11169297e-02 5.33993441e-05 9.95578859e-01
 1.61974153e-04 3.87251440e-02]
Linha: 26660 Epoca: 0 Erros: 3561  Acerto: 86.64291072768192 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.03684880e-02 3.21077201e-06 9.10161837e-04 1.53589038e-03
 9.71394662e-05 3.68607051e-02 4.56559657e-05 9.85854111e-01
 2.01665149e-04 5.73113589e-02]
Linha: 26680 Epoca: 0 Erros: 3561  Acerto: 86.65292353823088 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.22128325e-04 6.10992279e-05 1.22804557e-02 4.15740650e-03
 3.65082313e-04 4.22521040e-04 4.21914227e-05 9.95916769e-01
 3.55625579e-04 4.04544485e-02]
Linha: 26700 Epoca: 0 Erros: 3562  Ace

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[6.97023866e-04 2.99421527e-04 7.96563000e-03 9.90351522e-01
 5.33673646e-06 1.89677931e-03 9.27227957e-06 4.86812215e-03
 5.47335339e-02 1.08677856e-03]
Linha: 27280 Epoca: 0 Erros: 3614  Acerto: 86.75219941348973 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.85286869e-02 2.68016030e-05 2.98170198e-05 7.39046600e-02
 2.27942764e-04 4.61930442e-01 5.17248801e-04 1.85551965e-04
 3.57871037e-01 1.19151002e-02]
Linha: 27300 Epoca: 0 Erros: 3616  Acerto: 86.75457875457876 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[4.17930827e-04 2.42652470e-05 4.16491146e-03 9.17339568e-07
 1.85804453e-02 3.09179069e-04 9.94022990e-01 8.42765187e-04
 5.04008862e-04 3.69451307e-04]
Linha: 27320 Epoca: 0 Erros: 3617  Acerto: 86.7606149341142 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[2.05839968e-05 3.69847133e-04 1.99727095e-03 2.88725983e-06
 2.04580353e-02 2.37453350e-05 9.69153406e-01 2.30000016e-03
 5.47284680e-03 1.02623145e-02]
Linha: 27340 Epoca: 0 Erros: 3619  Ace

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.49246961e-04 3.48183722e-05 1.44625638e-03 9.17747042e-06
 9.99414685e-01 7.07985045e-04 2.10649997e-02 5.73111060e-03
 2.56707326e-03 4.82133485e-03]
Linha: 27920 Epoca: 0 Erros: 3669  Acerto: 86.85888252148997 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.08509239e-04 1.92387370e-04 1.12208115e-01 1.66054515e-03
 1.59977518e-01 1.75860640e-04 2.09949555e-02 2.20743527e-04
 2.91158787e-01 7.63245076e-03]
Linha: 27940 Epoca: 0 Erros: 3670  Acerto: 86.86471009305654 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[3.63202736e-04 6.73772347e-06 3.04717302e-03 4.80343742e-05
 9.97644634e-01 1.86718329e-03 7.25907816e-03 5.34941143e-03
 7.44018895e-03 1.00575780e-02]
Linha: 27960 Epoca: 0 Erros: 3670  Acerto: 86.87410586552218 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.61539522e-04 5.61577587e-06 3.49332603e-03 2.19691447e-05
 9.97731704e-01 8.72466059e-04 2.01053461e-02 6.67091766e-03
 3.41906438e-03 3.24869766e-03]
Linha: 27980 Epoca: 0 Erros: 3672  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.21685170e-03 2.75659589e-03 9.68752106e-01 8.13684437e-02
 1.38398306e-06 2.87888517e-04 1.72285839e-03 4.55594346e-05
 1.87450112e-02 1.89434479e-04]
Linha: 28560 Epoca: 0 Erros: 3710  Acerto: 87.00980392156862 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.63044451e-02 3.35392893e-05 1.51505087e-05 1.58346483e-02
 8.89268889e-06 9.86871347e-01 7.70824034e-05 6.92386024e-04
 1.10444054e-02 2.18761397e-02]
Linha: 28580 Epoca: 0 Erros: 3710  Acerto: 87.0188943317005 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.89270355e-05 7.98753887e-05 5.74399779e-05 4.55753420e-04
 8.52857993e-01 1.88294928e-02 3.16340071e-03 1.04798429e-03
 1.31853936e-01 2.29521093e-01]
Linha: 28600 Epoca: 0 Erros: 3712  Acerto: 87.02097902097901 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[2.19927331e-04 7.25037066e-05 6.43117054e-03 2.76500935e-06
 2.94091385e-02 3.87582868e-03 9.87476229e-01 1.62122055e-04
 1.51741809e-04 2.39666129e-02]
Linha: 28620 Epoca: 0 Erros: 3714  Ace

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.92243103e-01 9.32814541e-06 3.30121097e-03 2.88111122e-03
 4.05573329e-06 1.51882388e-02 1.91108198e-04 2.80313399e-03
 7.60765076e-04 2.74438457e-05]
Linha: 29200 Epoca: 0 Erros: 3764  Acerto: 87.10958904109589 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.78250583e-02 2.64482177e-05 6.31283838e-01 7.41497726e-05
 4.41090005e-05 7.96042679e-02 6.41475802e-03 9.76748312e-04
 1.65289335e-02 5.26934298e-05]
Linha: 29220 Epoca: 0 Erros: 3767  Acerto: 87.10814510609171 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.03241038e-04 8.99042680e-01 4.59081209e-02 5.68554347e-03
 1.55404933e-04 5.30454766e-03 9.63309038e-04 3.96922879e-03
 1.35349880e-01 1.32990070e-05]
Linha: 29240 Epoca: 0 Erros: 3770  Acerto: 87.10670314637483 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.20840214e-04 4.34114587e-04 7.21875732e-05 2.48589018e-01
 6.05887876e-05 1.38841859e-02 2.89116274e-04 5.71440859e-02
 2.98258156e-01 3.17191977e-02]
Linha: 29260 Epoca: 0 Erros: 3770  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.22332070e-03 1.92498795e-05 7.25717594e-03 6.43407583e-06
 2.10220291e-01 1.13444415e-01 5.11621481e-01 1.72000597e-03
 3.45424937e-03 3.99586691e-04]
Linha: 29840 Epoca: 0 Erros: 3819  Acerto: 87.20174262734585 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[7.03309115e-05 6.87436645e-03 4.47779363e-03 2.50596149e-03
 4.78325000e-05 3.25771637e-03 2.82183812e-05 8.53360342e-01
 3.06405032e-03 8.89353030e-02]
Linha: 29860 Epoca: 0 Erros: 3819  Acerto: 87.21031480241125 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.07961889e-05 4.27744911e-03 4.33693900e-05 2.41818516e-03
 3.90680937e-01 4.15318935e-02 6.46396563e-04 2.78469232e-03
 4.36191576e-01 4.36263861e-02]
Linha: 29880 Epoca: 0 Erros: 3823  Acerto: 87.20548862115128 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.97856466e-03 6.91415344e-02 1.39872743e-02 1.13426468e-01
 1.14285659e-02 2.80894875e-01 4.33585115e-03 5.37433986e-05
 2.59190998e-02 2.86017686e-06]
Linha: 29900 Epoca: 0 Erros: 3825  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[7.57552888e-04 8.89554203e-05 1.05701621e-05 3.11635804e-04
 4.60211081e-04 1.93055140e-03 1.78075665e-04 9.76069281e-01
 9.55727597e-03 1.17998754e-01]
Linha: 30480 Epoca: 0 Erros: 3879  Acerto: 87.27362204724409 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[9.02501641e-03 3.38182184e-04 1.30583982e-02 4.88389296e-05
 2.26657991e-02 6.26203991e-01 8.52976965e-03 4.56569341e-04
 3.81913512e-02 1.46407406e-03]
Linha: 30500 Epoca: 0 Erros: 3880  Acerto: 87.27868852459017 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[9.82881263e-03 5.43070859e-05 1.02526913e-03 7.38261019e-05
 5.75304862e-04 4.19981052e-02 1.41900937e-02 2.94418928e-05
 9.69823729e-01 6.37244951e-02]
Linha: 30520 Epoca: 0 Erros: 3882  Acerto: 87.28047182175622 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[9.60799594e-03 5.51602188e-05 1.38856345e-02 1.23623160e-05
 2.42177621e-04 1.24960938e-02 3.59460791e-02 1.11291374e-04
 9.68815524e-01 4.06287655e-02]
Linha: 30540 Epoca: 0 Erros: 3884  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[4.00432283e-03 3.49846719e-05 1.17059739e-02 5.05956564e-03
 8.82761787e-04 1.96921890e-02 1.26714290e-03 9.94924436e-06
 9.92309540e-01 9.87625082e-03]
Linha: 31120 Epoca: 0 Erros: 3941  Acerto: 87.33611825192803 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[5.48635658e-04 6.23039634e-03 1.79213696e-03 1.19034076e-03
 3.42881334e-03 3.07082749e-02 2.40052750e-04 1.36931362e-03
 9.21870602e-01 1.77490194e-02]
Linha: 31140 Epoca: 0 Erros: 3943  Acerto: 87.33782915863841 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.94821511e-04 9.97749195e-06 3.89629602e-04 1.79545876e-06
 9.91642457e-01 7.28512064e-04 1.37495080e-02 9.81622230e-03
 1.11623480e-02 3.71321022e-02]
Linha: 31160 Epoca: 0 Erros: 3944  Acerto: 87.34274711168165 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.50650486e-06 9.71010795e-01 1.31965785e-02 1.21121511e-02
 3.82915882e-05 1.18325022e-03 4.78323665e-03 3.57038749e-03
 1.61360839e-02 3.68954701e-03]
Linha: 31180 Epoca: 0 Erros: 3944  Ac

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[4.66303034e-04 7.04344628e-04 1.82867722e-04 8.98469870e-01
 2.69328305e-05 3.95540000e-01 4.06709010e-04 1.84409052e-04
 1.16051643e-01 1.90372348e-03]
Linha: 31760 Epoca: 0 Erros: 4006  Acerto: 87.38664987405542 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[3.82318510e-03 1.41506331e-05 1.31943302e-04 1.32268260e-01
 6.64797680e-04 9.18627940e-01 1.48836531e-03 3.93314646e-05
 3.19542416e-02 1.24238618e-02]
Linha: 31780 Epoca: 0 Erros: 4008  Acerto: 87.3882945248584 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.21704343e-05 2.18932449e-03 5.21500592e-03 1.05497000e-01
 4.70414894e-04 4.82476725e-04 4.95428435e-06 9.94841646e-01
 1.45835575e-04 6.99206887e-03]
Linha: 31800 Epoca: 0 Erros: 4011  Acerto: 87.38679245283019 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[6.61479132e-03 2.75095627e-05 2.10882249e-03 1.42240557e-03
 2.80837468e-03 9.15309226e-01 1.16626809e-02 4.55280320e-06
 3.87124064e-01 8.16937910e-05]
Linha: 31820 Epoca: 0 Erros: 4012  Ace

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.58066495e-01 7.71204556e-07 4.60052137e-03 3.87138851e-03
 2.83388175e-05 4.16172380e-03 2.02104050e-03 3.47736328e-04
 5.83811852e-03 4.57679409e-04]
Linha: 32400 Epoca: 0 Erros: 4072  Acerto: 87.4320987654321 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.00307166e-03 6.99087750e-06 1.10121752e-04 6.94120889e-06
 5.82077860e-02 1.23259763e-03 2.08047075e-02 5.78498783e-03
 2.20404061e-02 9.60532664e-01]
Linha: 32420 Epoca: 0 Erros: 4077  Acerto: 87.42442936458976 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.64617633e-06 9.79078971e-01 3.97977052e-02 7.51318732e-03
 4.67569129e-03 2.07167406e-03 2.09166315e-04 4.72248541e-02
 2.61324637e-03 6.49692081e-04]
Linha: 32440 Epoca: 0 Erros: 4079  Acerto: 87.42601726263871 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4.61912075e-01 3.55945014e-05 5.70065140e-01 6.40157430e-02
 1.11890184e-04 2.03791294e-03 1.42733307e-03 8.46044833e-05
 3.59637529e-03 9.03253715e-05]
Linha: 32460 Epoca: 0 Erros: 4085  Ace

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.39977534e-03 1.89510148e-05 6.81842221e-04 4.40735065e-04
 5.55906280e-04 1.53968979e-01 4.69504584e-04 8.41663688e-05
 9.90892846e-01 1.31104808e-02]
Linha: 33040 Epoca: 0 Erros: 4123  Acerto: 87.52118644067797 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.12035369e-02 1.81855867e-05 1.42253726e-03 4.04625314e-04
 1.61278175e-04 7.59867382e-03 9.20553317e-04 5.59666552e-02
 4.07219447e-01 2.48339041e-01]
Linha: 33060 Epoca: 0 Erros: 4125  Acerto: 87.52268602540835 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.93928051e-01 2.00823233e-06 3.79057113e-04 2.83014165e-03
 9.50684602e-06 6.50438597e-02 4.26614773e-03 1.19323676e-03
 2.62338555e-04 1.53365396e-04]
Linha: 33080 Epoca: 0 Erros: 4126  Acerto: 87.52720677146311 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[9.11303654e-03 2.17798642e-05 5.71764275e-03 3.55076660e-01
 2.36996529e-06 8.58723850e-02 7.23869149e-05 1.23030334e-03
 2.56785264e-01 8.38381301e-04]
Linha: 33100 Epoca: 0 Erros: 4126  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.99719278e-05 2.11668485e-04 5.78273489e-05 1.78115101e-04
 9.75191194e-01 8.63025584e-03 8.71505563e-04 2.14269015e-02
 1.23082238e-02 1.08478006e-01]
Linha: 33680 Epoca: 0 Erros: 4168  Acerto: 87.62470308788599 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.97043238e-05 3.77501931e-04 1.05720895e-04 1.01949914e-03
 2.25036497e-02 2.33990878e-03 4.25832495e-04 4.92373668e-02
 2.10008159e-02 9.27588058e-01]
Linha: 33700 Epoca: 0 Erros: 4169  Acerto: 87.62908011869436 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.31652370e-03 1.39858073e-04 1.69393566e-02 4.19404217e-03
 2.01477295e-04 3.44510141e-03 4.17607205e-04 1.85816971e-04
 9.90417657e-01 7.56265513e-03]
Linha: 33720 Epoca: 0 Erros: 4169  Acerto: 87.63641755634639 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.96563872e-01 8.44949389e-07 3.98522621e-03 1.26462607e-03
 1.68362293e-05 1.25213279e-02 1.11481092e-03 1.86098302e-03
 4.07210984e-04 1.14994721e-04]
Linha: 33740 Epoca: 0 Erros: 4170  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[7.70721593e-05 4.58072803e-03 2.82083613e-03 1.45290041e-02
 1.48217631e-03 2.21519877e-02 2.90281643e-03 9.28412282e-05
 9.88175180e-01 2.02152301e-02]
Linha: 34320 Epoca: 0 Erros: 4196  Acerto: 87.77389277389277 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[2.52601382e-03 4.92084597e-06 1.18866055e-03 3.19421718e-04
 5.27892546e-03 2.20201265e-04 1.07009106e-02 5.80827470e-03
 3.19182032e-02 9.81092563e-01]
Linha: 34340 Epoca: 0 Erros: 4197  Acerto: 87.77810133954571 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.35964938e-06 9.90261388e-01 1.39402081e-03 2.83886744e-02
 6.45311281e-06 7.02743350e-03 4.47489269e-03 1.09594430e-02
 3.35169618e-03 2.61520625e-02]
Linha: 34360 Epoca: 0 Erros: 4198  Acerto: 87.78230500582072 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.35765062e-05 9.58434621e-05 5.39448309e-05 9.08577583e-06
 9.79703325e-01 2.76515380e-03 1.60816359e-02 4.02878085e-02
 1.57231963e-03 2.87787060e-02]
Linha: 34380 Epoca: 0 Erros: 4200  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.90761153e-03 6.29605207e-05 4.87085885e-05 7.37581614e-04
 9.83633906e-05 5.38611010e-03 1.42503485e-05 9.83960385e-01
 2.20227545e-03 3.74643464e-02]
Linha: 34960 Epoca: 0 Erros: 4265  Acerto: 87.80034324942793 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.18000280e-03 1.32348817e-03 4.62495279e-03 4.13740609e-03
 3.01827778e-04 8.75838893e-03 1.36310586e-03 8.81316850e-06
 9.92637094e-01 2.28637202e-03]
Linha: 34980 Epoca: 0 Erros: 4266  Acerto: 87.80445969125215 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.92660618e-01 1.35243465e-06 1.56519398e-02 1.06011231e-02
 2.22759112e-05 3.48043883e-03 4.58088905e-04 6.40118201e-03
 7.97210071e-04 7.09072588e-04]
Linha: 35000 Epoca: 0 Erros: 4267  Acerto: 87.80857142857143 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.12830054e-03 3.72585938e-06 5.38720770e-05 5.95068062e-05
 3.55845846e-02 1.46993208e-04 8.97575371e-04 2.76872665e-02
 1.71762347e-02 9.78437920e-01]
Linha: 35020 Epoca: 0 Erros: 4267  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.38714418e-02 1.05933858e-05 9.96376751e-01 1.38256667e-03
 7.28977690e-04 1.66550625e-04 2.88541367e-02 4.78855091e-06
 1.50645015e-03 1.85609352e-05]
Linha: 35600 Epoca: 0 Erros: 4305  Acerto: 87.90730337078652 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.11709225e-03 8.62084565e-05 1.88833194e-04 3.38128418e-03
 1.18811553e-02 2.05261312e-02 2.37406675e-04 2.95979600e-04
 7.87337189e-01 1.03287982e-01]
Linha: 35620 Epoca: 0 Erros: 4307  Acerto: 87.90847838293094 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.95657032e-01 1.46318897e-06 1.36111483e-03 3.44064481e-03
 7.27560269e-06 7.01310623e-03 4.75375613e-04 5.27156686e-03
 2.70596364e-04 1.96587683e-05]
Linha: 35640 Epoca: 0 Erros: 4310  Acerto: 87.90684624017958 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.96204476e-01 3.30960139e-06 4.98218527e-04 1.49523836e-02
 1.79547262e-05 2.35014744e-03 3.98310997e-04 1.33011861e-02
 5.06440131e-05 3.29400982e-05]
Linha: 35660 Epoca: 0 Erros: 4311  Ac

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.50204841e-06 8.63416181e-01 7.10976593e-03 2.11511067e-03
 3.29203681e-04 9.63097390e-04 4.92291553e-03 1.28822211e-02
 2.05788707e-02 3.19342094e-03]
Linha: 36240 Epoca: 0 Erros: 4342  Acerto: 88.0187637969095 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[5.03471205e-04 9.46530339e-06 1.16037816e-02 1.48583742e-05
 1.84039891e-03 1.30442266e-04 9.82483343e-01 1.37874919e-05
 2.63430644e-03 7.84070331e-03]
Linha: 36260 Epoca: 0 Erros: 4343  Acerto: 88.02261445118587 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.10069807e-05 1.84343121e-04 5.98156948e-06 9.50173136e-06
 6.76499204e-01 1.03052258e-03 3.89243165e-02 3.56398944e-03
 2.47826887e-03 9.12421212e-02]
Linha: 36280 Epoca: 0 Erros: 4344  Acerto: 88.02646085997795 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[7.56411831e-03 1.64320972e-05 5.56288476e-03 1.84672298e-03
 5.88455194e-04 5.74080552e-03 9.24750885e-05 7.35871211e-04
 9.65823671e-01 1.49827010e-03]
Linha: 36300 Epoca: 0 Erros: 4344  Ace

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.84040427e-04 5.92967060e-04 9.97924291e-01 2.03514884e-03
 2.56980374e-06 5.45497791e-05 4.71744189e-02 1.01780637e-03
 2.95743837e-03 1.68186204e-05]
Linha: 36880 Epoca: 0 Erros: 4371  Acerto: 88.14804772234274 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[8.53598499e-05 1.00379646e-03 3.48450548e-04 9.91570640e-01
 2.12483387e-05 6.49991030e-03 1.10707126e-04 2.30116180e-03
 3.34285034e-02 2.56208708e-03]
Linha: 36900 Epoca: 0 Erros: 4374  Acerto: 88.14634146341463 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.98809355e-01 1.26245376e-06 3.59372927e-03 3.04839932e-04
 2.49459654e-06 8.69554706e-03 2.22036517e-03 7.03277590e-04
 8.42812014e-04 5.90499044e-06]
Linha: 36920 Epoca: 0 Erros: 4376  Acerto: 88.14734561213434 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.94501827e-02 9.28617667e-04 5.81991946e-04 6.34585327e-03
 3.76523581e-05 9.87512766e-01 4.81407048e-03 2.10966207e-05
 1.05987595e-01 4.99698282e-04]
Linha: 36940 Epoca: 0 Erros: 4378  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[6.48250378e-06 1.86945427e-04 3.75077784e-04 1.56139019e-03
 9.60668991e-01 9.77512711e-03 3.77477056e-04 6.52684249e-03
 4.03992867e-03 3.45043209e-02]
Linha: 37520 Epoca: 0 Erros: 4440  Acerto: 88.16631130063966 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[7.79242057e-04 1.69573338e-03 4.76711298e-02 4.09198840e-04
 4.23465823e-04 9.36263610e-03 5.71656777e-04 7.36526244e-05
 9.91780716e-01 5.60086358e-04]
Linha: 37540 Epoca: 0 Erros: 4442  Acerto: 88.16728822589238 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.92497965e-01 7.74678114e-07 1.24252783e-02 1.93648523e-04
 5.07957796e-07 4.23575250e-02 1.22787184e-03 1.05846533e-03
 2.72100656e-04 2.15988886e-05]
Linha: 37560 Epoca: 0 Erros: 4447  Acerto: 88.16027689030884 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.77164605e-07 9.92601174e-01 1.34250701e-03 7.58935017e-03
 1.17876904e-05 1.15039147e-02 7.64673898e-04 4.70621301e-03
 3.24919295e-03 2.21526146e-02]
Linha: 37580 Epoca: 0 Erros: 4448  Ac

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.21024738e-05 9.82419971e-01 6.08705586e-02 3.51628020e-03
 6.32725899e-04 2.23149780e-03 1.56224768e-03 1.25749767e-02
 9.25194543e-03 5.38692422e-04]
Linha: 38160 Epoca: 0 Erros: 4490  Acerto: 88.23375262054508 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.97626999e-01 2.83614605e-07 2.04572238e-02 2.47644363e-04
 1.28776512e-05 5.33312856e-03 5.43388118e-03 4.35508997e-04
 8.47359157e-04 8.48519169e-05]
Linha: 38180 Epoca: 0 Erros: 4490  Acerto: 88.23991618648508 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.14747527e-03 4.41878767e-05 2.42851086e-01 9.77492057e-01
 6.24021498e-06 2.79732378e-02 8.32692916e-05 7.66444906e-05
 9.56709293e-03 5.70165912e-06]
Linha: 38200 Epoca: 0 Erros: 4491  Acerto: 88.2434554973822 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.16231741e-01 2.61545109e-07 4.05809572e-02 1.39627036e-04
 5.58142097e-03 7.32498194e-03 4.64000292e-01 8.10856757e-04
 6.86201120e-06 4.36440573e-05]
Linha: 38220 Epoca: 0 Erros: 4491  Ace

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[6.10769050e-04 6.31009984e-04 7.21251638e-04 1.51729519e-02
 1.30068912e-03 5.12273354e-02 8.31199706e-04 1.46827780e-04
 9.90319103e-01 1.19853782e-03]
Linha: 38800 Epoca: 0 Erros: 4546  Acerto: 88.28350515463917 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.44970970e-04 2.84504112e-05 1.90077618e-02 3.00106048e-03
 3.13530871e-05 1.16467065e-03 2.81014956e-06 9.94449569e-01
 1.48847497e-04 3.70218754e-03]
Linha: 38820 Epoca: 0 Erros: 4546  Acerto: 88.28954147346728 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.48883082e-04 4.48286472e-04 9.73784288e-01 1.26936667e-03
 9.61504876e-02 1.64692429e-04 6.67919208e-03 5.59581313e-05
 7.36209586e-04 9.45077470e-04]
Linha: 38840 Epoca: 0 Erros: 4547  Acerto: 88.29299691040165 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.97339563e-03 5.83908832e-04 1.42805086e-01 9.80423248e-01
 1.90448958e-06 5.06590678e-03 1.59475091e-04 3.45618122e-05
 7.83811445e-03 2.41884118e-05]
Linha: 38860 Epoca: 0 Erros: 4547  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[5.64657066e-04 2.61071261e-04 1.65746759e-01 1.10801429e-02
 1.58559795e-06 7.05123386e-04 1.11232246e-06 9.27414869e-01
 2.81498183e-03 3.65228745e-03]
Linha: 39440 Epoca: 0 Erros: 4592  Acerto: 88.35699797160244 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[5.03327756e-03 2.17770710e-06 4.03742763e-05 1.41282735e-03
 1.32296721e-05 1.88071746e-02 2.02531840e-05 9.91113046e-01
 4.32384157e-04 1.15191818e-02]
Linha: 39460 Epoca: 0 Erros: 4593  Acerto: 88.36036492650786 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.57546035e-03 3.05137632e-03 1.17811750e-02 6.29061603e-03
 3.39519042e-05 1.72261302e-02 2.57693679e-04 1.43464738e-04
 9.92050996e-01 1.47116779e-03]
Linha: 39480 Epoca: 0 Erros: 4595  Acerto: 88.3611955420466 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.75588128e-02 3.54252619e-02 4.40100664e-04 4.22359991e-04
 7.67607931e-05 1.85660869e-01 8.16794880e-04 4.98053333e-04
 9.06595488e-01 1.01485761e-02]
Linha: 39500 Epoca: 0 Erros: 4596  Ace

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.72097359e-01 7.55264534e-05 1.61524815e-01 6.81172854e-02
 6.18862875e-06 1.67498280e-04 5.75903083e-04 1.12174817e-03
 2.47703190e-02 7.13722268e-04]
Linha: 40080 Epoca: 0 Erros: 4630  Acerto: 88.44810379241517 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.98755736e-01 3.74460162e-07 7.15010434e-03 1.16438460e-03
 5.74239851e-06 5.94625250e-03 8.38782093e-04 3.60821316e-03
 3.56855844e-04 4.87263467e-05]
Linha: 40100 Epoca: 0 Erros: 4632  Acerto: 88.44887780548629 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[8.29857993e-03 1.53955652e-04 9.86967036e-01 2.44924375e-02
 2.45380535e-05 7.82792982e-05 2.99783667e-03 1.63239184e-05
 2.01827658e-02 7.19266644e-05]
Linha: 40120 Epoca: 0 Erros: 4633  Acerto: 88.45214356929212 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.48419336e-02 4.81030856e-06 2.87759018e-02 2.09758294e-04
 8.52210063e-04 3.99779371e-02 9.48262024e-01 1.19778444e-04
 3.15957272e-05 3.92563763e-05]
Linha: 40140 Epoca: 0 Erros: 4637  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.05555502e-03 1.16473309e-06 8.68245934e-04 1.32858942e-07
 9.85680742e-01 3.13315564e-04 6.04915631e-03 3.67946938e-02
 1.10657304e-03 8.90394849e-03]
Linha: 40720 Epoca: 0 Erros: 4677  Acerto: 88.51424361493123 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.75071991e-03 2.14165108e-03 3.45682704e-04 9.35057854e-01
 2.91476274e-05 2.93415771e-01 3.98706925e-05 8.51149342e-04
 3.23914362e-03 9.80103989e-07]
Linha: 40740 Epoca: 0 Erros: 4678  Acerto: 88.51742758959254 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[2.74579533e-03 1.42954045e-03 1.23898174e-03 1.39528802e-02
 1.74863362e-02 9.78349355e-01 7.47135949e-04 3.05423343e-04
 1.65250625e-03 3.22967413e-06]
Linha: 40760 Epoca: 0 Erros: 4679  Acerto: 88.52060843964671 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.32803663e-06 9.88623449e-01 4.15507704e-03 1.13203516e-02
 3.27247147e-03 4.76761139e-03 2.95209614e-04 3.41909618e-02
 2.78209770e-03 1.61242354e-03]
Linha: 40780 Epoca: 0 Erros: 4680  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.41742262e-03 2.01118017e-03 7.01677190e-04 2.34149162e-03
 3.10769551e-04 1.67150309e-02 7.57563155e-03 6.40829655e-05
 8.79223239e-01 3.46920973e-02]
Linha: 41360 Epoca: 0 Erros: 4724  Acerto: 88.57833655705996 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.84992237e-04 6.91300189e-03 3.72243036e-05 3.11734120e-04
 2.37824345e-04 3.13780431e-03 2.12637235e-04 6.10797836e-01
 4.34014377e-03 7.38022622e-01]
Linha: 41380 Epoca: 0 Erros: 4726  Acerto: 88.57902368293861 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.82369124e-04 7.72877379e-04 8.67764144e-01 3.19733748e-05
 6.27130067e-04 8.09612879e-05 4.51281399e-04 7.26377359e-02
 6.10396842e-03 5.92034145e-03]
Linha: 41400 Epoca: 0 Erros: 4727  Acerto: 88.58212560386474 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[6.30363144e-05 9.27593992e-01 2.59820370e-02 7.07440730e-03
 8.78324002e-04 1.67161587e-03 1.22399839e-04 1.19570123e-02
 2.12002674e-02 9.89472049e-04]
Linha: 41420 Epoca: 0 Erros: 4729  Ac

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.42931859e-02 1.99403717e-06 1.82665751e-03 5.15813574e-07
 2.42519449e-02 5.34596355e-04 2.41320372e-01 2.66538862e-04
 4.39207647e-03 2.62455808e-03]
Linha: 42000 Epoca: 0 Erros: 4774  Acerto: 88.63333333333333 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.05900818e-03 1.67685718e-04 9.86268154e-01 2.03348925e-03
 2.53981362e-06 1.02238407e-04 1.16387550e-02 2.53039118e-05
 1.27229390e-02 1.65160039e-04]
Linha: 42020 Epoca: 0 Erros: 4776  Acerto: 88.63398381722989 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.87127555e-06 9.97093410e-01 6.94146160e-03 1.90344075e-03
 1.19368186e-03 1.65944168e-03 1.52218123e-03 5.59465798e-03
 6.34537166e-03 1.19703320e-03]
Linha: 42040 Epoca: 0 Erros: 4778  Acerto: 88.63463368220742 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[4.13732358e-04 2.88512828e-05 3.54620145e-04 3.90822522e-04
 1.17795786e-01 5.54421671e-02 5.48555740e-03 1.26907428e-04
 8.21601382e-02 1.03414271e-01]
Linha: 42060 Epoca: 0 Erros: 4780  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.76343660e-03 3.42036505e-06 8.66001183e-02 2.76647838e-02
 4.06828264e-06 3.33719580e-04 6.14465272e-06 9.68737745e-01
 1.30894563e-05 1.28631465e-03]
Linha: 42640 Epoca: 0 Erros: 4827  Acerto: 88.6796435272045 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[6.01442685e-02 2.41421757e-05 2.15716627e-03 6.16449910e-03
 9.68409198e-06 9.25627282e-01 2.99211869e-02 3.53423326e-06
 2.17948575e-03 1.81110335e-04]
Linha: 42660 Epoca: 0 Erros: 4827  Acerto: 88.68495077355837 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[4.38615909e-03 2.49777954e-05 1.32055860e-03 1.04708696e-03
 4.47069564e-04 2.11543240e-02 6.64550173e-05 1.59052016e-04
 9.96560068e-01 1.68904892e-02]
Linha: 42680 Epoca: 0 Erros: 4830  Acerto: 88.68322399250235 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.15147774e-02 8.54102588e-06 1.46171424e-02 3.38995562e-04
 2.84015819e-04 4.09844450e-03 1.46199986e-03 1.94310049e-05
 9.96271384e-01 5.47809207e-03]
Linha: 42700 Epoca: 0 Erros: 4833  Ace

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.80087545e-03 1.81655429e-06 3.12419236e-06 5.93685226e-05
 5.29932213e-03 1.26362287e-02 2.19016561e-05 9.97446797e-01
 1.25521560e-04 3.83574626e-03]
Linha: 43280 Epoca: 0 Erros: 4882  Acerto: 88.71996303142329 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.71396146e-04 9.46367692e-03 5.16300261e-03 7.97928085e-03
 2.50791337e-05 7.64648518e-03 1.26020883e-02 5.84058031e-05
 9.82038090e-01 4.43739103e-03]
Linha: 43300 Epoca: 0 Erros: 4882  Acerto: 88.72517321016167 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[2.31712666e-02 4.74920347e-06 1.28849655e-04 1.16296815e-02
 4.93227357e-06 9.91563916e-01 1.20392491e-03 2.35670570e-05
 5.38906060e-03 2.35719016e-03]
Linha: 43320 Epoca: 0 Erros: 4882  Acerto: 88.730378578024 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.19054149e-05 9.64347605e-01 3.94424212e-02 3.73056156e-03
 3.67188726e-05 1.63788705e-02 1.76471541e-03 4.80026794e-04
 2.49794298e-02 7.09025298e-04]
Linha: 43340 Epoca: 0 Erros: 4883  Acer

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.27769791e-03 2.87390816e-06 3.34500080e-05 1.97505593e-04
 2.06542093e-04 6.94377111e-03 2.46120861e-05 9.24126748e-01
 4.70063373e-04 1.46506461e-01]
Linha: 43920 Epoca: 0 Erros: 4922  Acerto: 88.79326047358835 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.75162531e-01 8.93377661e-07 3.65172525e-03 8.54733132e-03
 1.63557700e-06 1.40952747e-02 1.47885379e-05 2.40140571e-03
 1.21733921e-03 1.30750301e-04]
Linha: 43940 Epoca: 0 Erros: 4922  Acerto: 88.7983614019117 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[2.87287142e-04 1.02909897e-03 5.58746128e-05 7.86197063e-04
 8.79879364e-02 7.69118420e-03 1.40135066e-03 5.98916778e-03
 5.34390956e-02 6.28759762e-01]
Linha: 43960 Epoca: 0 Erros: 4923  Acerto: 88.80118289353959 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[4.22217387e-05 2.38993441e-04 9.44643717e-03 1.22021530e-05
 1.03832320e-01 8.26749239e-04 6.57995214e-01 1.99505847e-03
 7.93310387e-04 7.85326227e-02]
Linha: 43980 Epoca: 0 Erros: 4923  Ace

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.77681466e-04 5.07634073e-05 1.08335389e-04 1.04716627e-02
 2.84372548e-02 2.07839769e-03 7.01733430e-04 2.72150917e-03
 5.81370811e-03 9.27933515e-01]
Linha: 44560 Epoca: 0 Erros: 4963  Acerto: 88.86220825852783 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.11567281e-04 1.81839189e-02 1.52847662e-03 1.72807923e-01
 1.15962127e-04 5.63706967e-03 6.77304971e-05 1.08143068e-03
 9.39558964e-01 1.08644170e-02]
Linha: 44580 Epoca: 0 Erros: 4964  Acerto: 88.86496186630777 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.17411586e-01 6.24082081e-07 1.74173803e-02 1.90584576e-03
 3.56864318e-05 3.10820953e-03 5.51694065e-02 2.14513486e-04
 9.24746194e-05 1.04580140e-04]
Linha: 44600 Epoca: 0 Erros: 4964  Acerto: 88.86995515695067 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.95985284e-01 1.35043576e-06 1.09955990e-02 1.23015649e-03
 3.34997545e-07 3.23394609e-03 2.07931598e-04 5.92663932e-04
 1.09015445e-03 1.09705743e-05]
Linha: 44620 Epoca: 0 Erros: 4964  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[4.48406686e-02 2.06990746e-06 2.77547556e-02 2.44677287e-04
 3.44752224e-03 9.32955927e-03 3.39618943e-03 1.55455140e-05
 9.75952710e-01 6.02300336e-03]
Linha: 45200 Epoca: 0 Erros: 5010  Acerto: 88.91592920353982 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.67167101e-05 3.64200268e-05 7.60241834e-05 7.91142064e-04
 9.89932134e-01 2.85709113e-03 9.24791235e-04 6.79368232e-02
 6.46933464e-04 1.75323477e-02]
Linha: 45220 Epoca: 0 Erros: 5012  Acerto: 88.91640866873065 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[3.87574962e-03 9.93794164e-05 1.65639958e-03 9.84277857e-01
 1.35376392e-06 5.02471660e-02 2.26825251e-05 5.72274841e-05
 1.17457730e-03 1.13252390e-05]
Linha: 45240 Epoca: 0 Erros: 5014  Acerto: 88.91688770999116 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.31783703e-04 2.02711217e-04 9.93706676e-01 4.17894889e-03
 2.65110320e-07 2.84830787e-03 7.17999768e-04 1.03781586e-03
 1.29975819e-02 2.10396906e-05]
Linha: 45260 Epoca: 0 Erros: 5014  Ac

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[5.41349842e-04 3.58082025e-04 5.18445860e-02 5.23581001e-05
 2.16304480e-02 1.83879698e-02 9.93148655e-01 2.11606501e-05
 1.62649919e-03 2.30255673e-04]
Linha: 45840 Epoca: 0 Erros: 5065  Acerto: 88.95069808027924 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[9.32239136e-05 1.01244115e-03 2.29725645e-04 3.36719103e-02
 1.62433370e-02 5.46895836e-02 5.99930536e-04 2.91287891e-04
 9.63691206e-01 2.27499415e-03]
Linha: 45860 Epoca: 0 Erros: 5065  Acerto: 88.95551679023114 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[8.93331940e-05 1.29858391e-05 1.79897142e-05 4.58954950e-02
 1.61120598e-01 4.53762980e-04 1.38585013e-03 9.03633849e-03
 7.85678384e-03 9.19624489e-01]
Linha: 45880 Epoca: 0 Erros: 5068  Acerto: 88.9537925021796 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5.62376578e-03 6.97259591e-05 4.81574189e-05 1.58730827e-02
 5.83734958e-06 8.49617606e-01 2.77632671e-02 9.58622877e-04
 2.64649361e-03 3.35233166e-03]
Linha: 45900 Epoca: 0 Erros: 5068  Ace

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.88537631e-01 2.22621103e-07 3.17877412e-03 6.41300615e-04
 6.97370521e-06 6.53262861e-03 2.00984020e-03 1.43466165e-03
 1.04773339e-04 4.99776224e-05]
Linha: 46480 Epoca: 0 Erros: 5126  Acerto: 88.97160068846816 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.26366235e-07 9.83485013e-01 8.05983094e-03 1.69641937e-03
 3.85428672e-06 1.94631747e-02 5.79903632e-03 5.27058124e-03
 5.74817253e-03 1.16026844e-03]
Linha: 46500 Epoca: 0 Erros: 5126  Acerto: 88.9763440860215 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[4.90353668e-04 2.81187106e-04 2.45187892e-03 1.14056625e-02
 1.64583774e-03 8.43244307e-03 8.78776831e-04 5.16555954e-06
 9.94486402e-01 5.73948260e-03]
Linha: 46520 Epoca: 0 Erros: 5126  Acerto: 88.9810834049871 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.50358847e-07 9.76387146e-01 5.60685767e-03 4.10308869e-03
 2.77685430e-05 2.54144700e-03 3.81659219e-03 6.04845115e-02
 7.55011640e-04 8.12000248e-04]
Linha: 46540 Epoca: 0 Erros: 5126  Acer

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.73027172e-05 9.24470187e-01 5.09870346e-02 2.42850450e-03
 3.84444418e-05 1.27657429e-02 7.38052613e-04 7.24306971e-03
 5.71354445e-02 1.67171363e-04]
Linha: 47120 Epoca: 0 Erros: 5154  Acerto: 89.06196943972836 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.82579441e-01 8.38579595e-08 3.35418699e-02 1.04615043e-03
 2.76510477e-05 3.89920182e-02 1.31658787e-03 8.32068250e-04
 1.32341248e-03 5.41525756e-04]
Linha: 47140 Epoca: 0 Erros: 5154  Acerto: 89.06661009758167 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.47193078e-03 8.05564643e-07 4.65527887e-02 5.35150546e-06
 6.34288258e-02 6.07413985e-04 4.58588119e-01 4.16464197e-03
 1.46682442e-04 5.89966588e-03]
Linha: 47160 Epoca: 0 Erros: 5157  Acerto: 89.06488549618321 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.87054224e-04 5.38678512e-05 1.67037550e-01 8.45720169e-07
 1.23752121e-02 1.30596149e-04 7.79012422e-01 4.86079891e-04
 1.49343528e-03 1.32946563e-02]
Linha: 47180 Epoca: 0 Erros: 5157  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[8.35269883e-01 1.77267374e-06 1.93369709e-02 5.89267654e-03
 1.12497582e-04 1.17196411e-03 5.10149766e-04 8.93300324e-05
 1.67658306e-01 4.10025876e-03]
Linha: 47760 Epoca: 0 Erros: 5208  Acerto: 89.09547738693468 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[7.09751533e-05 2.96481245e-05 2.29053237e-04 3.36984784e-05
 9.93644396e-01 1.13927600e-02 6.15642662e-03 1.54376086e-03
 1.63250146e-04 1.25011577e-02]
Linha: 47780 Epoca: 0 Erros: 5210  Acerto: 89.09585600669736 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[4.30458815e-06 9.81846373e-01 5.55462983e-02 4.13271973e-03
 4.28685459e-05 5.31569836e-03 1.59710659e-03 5.64181756e-03
 3.74287479e-03 3.33785133e-04]
Linha: 47800 Epoca: 0 Erros: 5211  Acerto: 89.09832635983264 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[7.37512514e-03 1.53716912e-05 9.98484730e-01 4.44736990e-03
 1.15975641e-05 1.30974839e-04 9.12572914e-03 2.63252235e-06
 4.66956424e-04 8.03933552e-06]
Linha: 47820 Epoca: 0 Erros: 5211  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.58776851e-05 1.82270285e-05 1.36482988e-03 5.62316229e-05
 9.98672137e-01 3.88627942e-02 1.16403624e-03 2.61354240e-04
 3.24333386e-03 3.17306473e-03]
Linha: 48400 Epoca: 0 Erros: 5250  Acerto: 89.15289256198346 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.96304711e-01 6.42745770e-07 3.07904421e-02 9.27638341e-05
 7.05921615e-07 2.51589290e-03 1.66850585e-03 1.32730684e-04
 1.66057808e-04 8.08088549e-06]
Linha: 48420 Epoca: 0 Erros: 5250  Acerto: 89.15737298636927 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.69974402e-01 1.12311070e-06 2.42436571e-03 2.42525332e-03
 4.10886330e-07 1.43242811e-02 2.66130251e-05 2.28218374e-03
 6.75836396e-04 4.66284023e-05]
Linha: 48440 Epoca: 0 Erros: 5250  Acerto: 89.16184971098266 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.96156169e-01 5.17692031e-07 4.58969710e-03 8.39144300e-04
 6.56928066e-07 4.76913166e-03 2.58672684e-04 8.43131314e-04
 2.16729047e-04 1.07702301e-04]
Linha: 48460 Epoca: 0 Erros: 5250  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[5.93075568e-05 5.38401348e-02 3.06356372e-04 4.77250494e-03
 4.21977816e-02 5.36555880e-02 1.91017977e-04 8.38438274e-03
 4.79098485e-03 2.98954193e-01]
Linha: 49040 Epoca: 0 Erros: 5291  Acerto: 89.21084828711255 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.71996795e-01 1.74731291e-07 3.06252752e-02 6.26525836e-04
 3.13658467e-04 1.84050021e-02 2.55067849e-03 6.07966347e-04
 1.06762946e-04 8.10553258e-05]
Linha: 49060 Epoca: 0 Erros: 5294  Acerto: 89.20913167549939 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[2.45080324e-03 1.01241709e-03 2.44373089e-02 7.65519682e-05
 6.18621072e-03 9.97847001e-01 2.45971638e-04 6.21353545e-04
 1.73561953e-03 9.32903839e-06]
Linha: 49080 Epoca: 0 Erros: 5297  Acerto: 89.20741646291768 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[5.37575904e-05 8.67731510e-01 3.35433145e-01 3.22010582e-04
 4.92434204e-04 3.32945281e-02 6.44859304e-04 1.78635734e-04
 2.53385039e-02 8.19679207e-05]
Linha: 49100 Epoca: 0 Erros: 5297  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[3.00022396e-04 7.07628437e-05 1.48425962e-03 1.36420501e-03
 8.36728083e-03 3.70387043e-03 5.27779108e-05 3.29917113e-02
 1.43787866e-01 7.08149775e-01]
Linha: 49680 Epoca: 0 Erros: 5342  Acerto: 89.24718196457327 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.76951608e-03 9.46889274e-05 1.07564905e-03 3.65904243e-04
 1.37882458e-03 2.13206999e-02 8.55871610e-01 1.20108084e-05
 3.75207610e-02 7.17731926e-03]
Linha: 49700 Epoca: 0 Erros: 5344  Acerto: 89.24748490945674 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[6.41636318e-04 1.15337104e-05 2.18026533e-04 6.93590512e-05
 7.05227395e-04 1.77612736e-02 3.58751877e-05 9.25247593e-01
 4.70818642e-03 1.00367633e-01]
Linha: 49720 Epoca: 0 Erros: 5345  Acerto: 89.24979887369268 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.51358363e-01 7.19396821e-06 1.58030668e-02 1.02371837e-03
 1.59706723e-08 3.95197378e-02 4.44610968e-04 1.41268312e-02
 1.16477856e-04 1.16389688e-04]
Linha: 49740 Epoca: 0 Erros: 5345  Ac

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[4.90684188e-03 1.62373388e-06 1.53086031e-03 2.61081865e-07
 6.91204371e-01 2.88437358e-03 1.91282418e-01 1.14632938e-02
 9.98167096e-03 2.82624874e-03]
Linha: 50320 Epoca: 0 Erros: 5388  Acerto: 89.29252782193959 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.00746340e-04 2.99852180e-06 1.14796271e-03 4.22854772e-07
 9.89957558e-01 1.71149609e-02 2.28100418e-03 5.64021599e-03
 1.01795699e-02 2.55538117e-02]
Linha: 50340 Epoca: 0 Erros: 5391  Acerto: 89.29082240762813 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[4.20364188e-05 7.75426859e-01 2.08613289e-01 9.37907453e-03
 2.64197746e-04 1.31403174e-03 6.82955320e-04 5.66905199e-03
 1.36453126e-02 4.18333518e-04]
Linha: 50360 Epoca: 0 Erros: 5393  Acerto: 89.291104050834 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.64383957e-01 3.16333575e-06 1.06968657e-02 5.41611263e-03
 3.95633971e-07 3.52678580e-02 6.58458719e-04 5.09923710e-04
 3.65699288e-05 7.76458907e-06]
Linha: 50380 Epoca: 0 Erros: 5396  Acer

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5.45129662e-03 3.42963784e-05 1.55996145e-03 1.00304436e-04
 2.51445672e-04 9.94340578e-01 1.65349876e-02 7.46710381e-06
 3.22407548e-03 1.93347960e-04]
Linha: 50960 Epoca: 0 Erros: 5434  Acerto: 89.33673469387755 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[4.35674268e-06 9.94491470e-01 2.38556405e-02 3.34906768e-03
 1.20692577e-04 2.39170913e-03 4.37670995e-03 9.66151889e-03
 2.53789721e-03 5.10248961e-04]
Linha: 50980 Epoca: 0 Erros: 5434  Acerto: 89.34091800706159 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.28809608e-02 3.06816563e-07 8.43408823e-05 1.80866099e-04
 1.45668074e-04 1.33224859e-02 2.55411939e-05 9.86713337e-01
 7.00358287e-05 2.87996900e-02]
Linha: 51000 Epoca: 0 Erros: 5434  Acerto: 89.34509803921569 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.12052141e-01 4.22459751e-07 2.31898116e-03 3.15578455e-03
 4.39231859e-04 3.63238652e-03 3.27736014e-03 1.61596040e-03
 1.18216466e-02 4.37739098e-02]
Linha: 51020 Epoca: 0 Erros: 5435  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.82733747e-04 2.08055479e-03 9.94865365e-01 1.47088697e-03
 7.65071773e-06 3.25031523e-04 3.62193994e-03 1.66318447e-04
 1.03948484e-02 2.66484225e-05]
Linha: 51600 Epoca: 0 Erros: 5463  Acerto: 89.41279069767442 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.75308737e-03 2.61350336e-06 7.81161608e-03 8.76062004e-06
 6.67501350e-04 7.07243402e-04 9.96125839e-01 2.60145659e-05
 3.42071075e-04 6.74117451e-04]
Linha: 51620 Epoca: 0 Erros: 5465  Acerto: 89.41301820999612 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[3.27452152e-02 1.68499718e-03 7.22112534e-04 4.62399738e-04
 3.74819337e-03 9.97230491e-01 1.16959164e-03 6.06841368e-04
 2.41084663e-02 2.02743725e-06]
Linha: 51640 Epoca: 0 Erros: 5465  Acerto: 89.41711851278079 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.01726191e-02 9.70314401e-02 8.70745772e-02 2.99716875e-04
 6.90053948e-05 8.61606037e-01 6.79373631e-04 5.08928842e-03
 1.68329942e-02 4.14440899e-06]
Linha: 51660 Epoca: 0 Erros: 5466  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[2.14757063e-05 3.19312668e-04 2.20193204e-05 1.08043544e-02
 2.34701567e-03 3.15262252e-03 4.40497848e-05 2.44277751e-02
 6.24827158e-02 9.83773568e-01]
Linha: 52240 Epoca: 0 Erros: 5502  Acerto: 89.46784073506892 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[2.20424074e-04 5.28781755e-02 2.43020037e-02 7.12675618e-01
 5.79463871e-05 2.14208764e-02 1.61588263e-04 5.13091372e-05
 4.86138052e-02 1.96185616e-04]
Linha: 52260 Epoca: 0 Erros: 5502  Acerto: 89.47187141216992 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[2.52430422e-06 3.55499572e-01 5.69142409e-04 4.43517477e-03
 1.76808998e-01 8.90211381e-02 8.52132969e-03 1.06303461e-03
 2.33336920e-02 3.13202447e-03]
Linha: 52280 Epoca: 0 Erros: 5504  Acerto: 89.47207345065034 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[8.51575731e-04 3.54490044e-07 4.40575737e-04 1.13588599e-05
 9.92947930e-01 9.89989991e-03 4.69893800e-03 2.69569281e-03
 1.18605969e-02 3.66165690e-03]
Linha: 52300 Epoca: 0 Erros: 5506  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.09490490e-04 1.18078820e-05 9.34828449e-02 7.33187446e-02
 3.77252137e-06 3.85733634e-04 3.41884693e-06 9.46331351e-01
 3.61387268e-04 4.59660321e-04]
Linha: 52880 Epoca: 0 Erros: 5550  Acerto: 89.50453857791226 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.19472099e-04 4.11490474e-04 8.92795962e-01 3.74478736e-01
 1.30730798e-06 1.72231890e-04 2.30673762e-04 9.43572006e-03
 8.07029287e-03 2.37956115e-05]
Linha: 52900 Epoca: 0 Erros: 5555  Acerto: 89.49905482041588 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[3.90681301e-05 8.49283485e-06 3.88280854e-03 1.39403938e-05
 9.99007737e-01 6.03045252e-03 3.86376320e-03 1.77441954e-03
 6.85719138e-03 8.52456896e-04]
Linha: 52920 Epoca: 0 Erros: 5558  Acerto: 89.4973544973545 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.77385137e-03 1.48435449e-05 7.54952803e-05 3.70756182e-01
 1.11635898e-05 2.47238032e-01 6.36151878e-05 7.19861100e-04
 4.22759428e-02 4.49960620e-03]
Linha: 52940 Epoca: 0 Erros: 5563  Ace

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[7.58092687e-04 2.87103311e-06 2.93235479e-03 1.49568172e-06
 9.97519427e-01 3.56459558e-03 2.78889663e-03 2.06117186e-02
 5.60457297e-04 6.47369471e-03]
Linha: 53520 Epoca: 0 Erros: 5595  Acerto: 89.54596412556054 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.86609758e-06 9.80358060e-01 1.83480860e-02 5.62247791e-03
 9.32765146e-05 2.06323267e-02 1.52394459e-03 1.61899318e-03
 6.98599587e-03 1.03709567e-03]
Linha: 53540 Epoca: 0 Erros: 5595  Acerto: 89.54986925663056 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1.44290484e-04 3.27762419e-05 1.66771187e-02 1.40111156e-06
 4.92107016e-01 2.27687960e-03 1.30411535e-03 6.65254929e-03
 6.90403283e-02 2.55109507e-02]
Linha: 53560 Epoca: 0 Erros: 5599  Acerto: 89.54630321135176 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[2.13737818e-04 1.47879595e-05 4.46875004e-02 1.58337840e-03
 5.01958321e-05 2.73080269e-04 1.86986903e-06 9.98468261e-01
 1.36603328e-05 6.98885396e-04]
Linha: 53580 Epoca: 0 Erros: 5601  Ac

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5.05887517e-04 2.79832270e-03 5.09828550e-06 2.33025605e-02
 7.19221632e-04 9.75889249e-01 3.55424996e-03 1.43147212e-04
 2.97898133e-03 4.88223342e-02]
Linha: 54160 Epoca: 0 Erros: 5642  Acerto: 89.58271787296898 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[8.87648051e-06 4.22932016e-04 5.17134131e-04 1.02059926e-04
 9.21113665e-01 5.47311173e-03 3.48714525e-04 1.52105413e-02
 8.71701471e-03 1.12542279e-01]
Linha: 54180 Epoca: 0 Erros: 5644  Acerto: 89.5828719084533 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.47975189e-05 1.18660358e-02 1.50413101e-03 9.90107611e-01
 3.29776821e-05 3.00883740e-03 1.60142351e-05 4.16607113e-03
 2.09139733e-02 8.32373413e-03]
Linha: 54200 Epoca: 0 Erros: 5646  Acerto: 89.58302583025831 %
_________
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[4.56004610e-04 1.48767671e-05 2.27743930e-04 2.11835378e-04
 1.03012024e-04 4.23724293e-03 2.08104394e-05 9.79139794e-01
 1.97796665e-04 1.78281678e-01]
Linha: 54220 Epoca: 0 Erros: 5646  Ace

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.34799496e-04 3.23330797e-05 4.88556517e-02 1.98317757e-06
 3.99190539e-03 7.98567275e-04 9.97952558e-01 7.23804792e-06
 1.82487243e-03 2.98837130e-04]
Linha: 54800 Epoca: 0 Erros: 5671  Acerto: 89.6514598540146 %
_________
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[8.43237720e-05 1.86969632e-05 9.56447159e-05 1.30059613e-03
 7.72815084e-01 4.35380670e-03 3.21550583e-04 1.30566401e-03
 3.43341503e-02 2.11151252e-01]
Linha: 54820 Epoca: 0 Erros: 5673  Acerto: 89.6515870120394 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.42025736e-03 1.71856798e-03 2.88547521e-04 1.16414772e-02
 5.10676850e-04 9.78232108e-01 1.03193079e-05 1.78245158e-03
 8.21574205e-02 2.52123761e-05]
Linha: 54840 Epoca: 0 Erros: 5673  Acerto: 89.65536105032822 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[2.00647086e-04 7.61000525e-05 4.12133334e-03 9.92014598e-01
 1.60704992e-05 1.39807486e-03 8.20369699e-06 5.00275149e-03
 4.19254036e-03 1.96442860e-03]
Linha: 54860 Epoca: 0 Erros: 5674  Acer

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[3.38147123e-04 2.93393735e-06 2.86937274e-04 1.51621772e-04
 1.27070479e-03 3.05925404e-03 1.75224145e-05 9.96503460e-01
 8.34044710e-04 3.84365499e-03]
Linha: 55440 Epoca: 0 Erros: 5715  Acerto: 89.69155844155844 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1.17915725e-02 9.33069758e-05 2.66495461e-04 3.53175181e-03
 4.89384429e-05 9.96415231e-01 4.81062728e-03 1.09664412e-05
 3.64200360e-03 2.12347549e-04]
Linha: 55460 Epoca: 0 Erros: 5715  Acerto: 89.69527587450415 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.95501556e-01 6.22410004e-07 2.91506208e-02 3.82331428e-03
 2.87859731e-07 5.65579913e-03 3.42068702e-04 5.46362857e-04
 1.78391464e-04 5.58070540e-06]
Linha: 55480 Epoca: 0 Erros: 5715  Acerto: 89.69899062725307 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.63983653e-05 9.57531787e-01 4.04438213e-02 7.71260463e-03
 8.89312119e-05 5.15408316e-03 1.84960388e-03 1.93675949e-02
 2.19517531e-03 2.97697918e-04]
Linha: 55500 Epoca: 0 Erros: 5717  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.58578364e-02 1.63368739e-06 9.86212611e-01 2.51774565e-03
 4.86458613e-04 2.15798795e-04 6.45072263e-03 1.05115950e-06
 4.75907991e-04 3.15213365e-04]
Linha: 56080 Epoca: 0 Erros: 5745  Acerto: 89.75570613409415 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.84358476e-05 9.72323926e-01 1.50210359e-02 1.08766064e-02
 3.60497744e-05 1.08998326e-02 7.93527842e-04 7.39893003e-04
 8.72226270e-03 1.19654110e-03]
Linha: 56100 Epoca: 0 Erros: 5747  Acerto: 89.75579322638146 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[3.23930208e-03 2.42467521e-06 7.23931185e-06 2.65764889e-03
 2.56276432e-05 9.95596120e-01 2.22163847e-04 1.18706785e-04
 8.24601214e-03 3.15513168e-04]
Linha: 56120 Epoca: 0 Erros: 5747  Acerto: 89.75944404846757 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[2.22877998e-03 6.43089615e-05 1.67811096e-03 9.89144426e-01
 1.53559348e-06 3.54068893e-02 1.05146748e-04 2.28430875e-05
 1.31460352e-02 1.54839786e-04]
Linha: 56140 Epoca: 0 Erros: 5747  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[3.53068578e-05 1.31145608e-04 9.93752420e-01 1.01652732e-01
 6.04673648e-07 2.05968844e-04 5.57240261e-04 2.45389513e-03
 3.18496047e-04 2.27290489e-05]
Linha: 56720 Epoca: 0 Erros: 5785  Acerto: 89.80077574047955 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[2.34299763e-05 6.15791290e-03 9.74166799e-01 1.37293348e-01
 3.78590922e-07 5.30131766e-04 3.68732281e-04 1.85623210e-03
 1.50255932e-03 1.53872697e-05]
Linha: 56740 Epoca: 0 Erros: 5785  Acerto: 89.8043708142404 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.19638553e-05 2.90924714e-02 9.96536229e-01 1.02085852e-02
 6.96255639e-07 3.94636954e-04 1.20695836e-03 5.76447455e-05
 2.09306554e-03 1.24336876e-05]
Linha: 56760 Epoca: 0 Erros: 5785  Acerto: 89.80796335447498 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[8.89676593e-07 9.94898913e-01 2.92020241e-02 1.10082965e-03
 3.11984575e-06 2.08015366e-02 6.71799084e-03 3.91633349e-04
 5.49014770e-03 3.96550946e-03]
Linha: 56780 Epoca: 0 Erros: 5786  Ace

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.92803833e-01 4.15023544e-07 3.07270640e-03 1.31204926e-04
 1.09595385e-04 1.53440353e-02 6.97357989e-04 2.57449088e-03
 4.00133873e-04 3.38256610e-05]
Linha: 57360 Epoca: 0 Erros: 5809  Acerto: 89.87273361227336 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[4.73085042e-03 1.48991729e-05 6.92250225e-02 1.89467199e-04
 5.70054626e-05 1.74625032e-02 8.81172399e-05 1.83884432e-03
 9.48053521e-01 7.74593641e-04]
Linha: 57380 Epoca: 0 Erros: 5809  Acerto: 89.87626350644824 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1.36683881e-04 1.61907637e-03 8.69055197e-03 9.96312215e-01
 3.53887563e-05 9.37833811e-03 2.23896921e-05 3.14719436e-05
 3.19312558e-02 3.92433406e-05]
Linha: 57400 Epoca: 0 Erros: 5811  Acerto: 89.87630662020906 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.60406725e-03 2.07718539e-06 3.90546614e-03 6.06900188e-07
 2.31065700e-02 3.14536164e-05 9.91329786e-01 1.30727560e-03
 1.27646143e-04 9.48677503e-03]
Linha: 57420 Epoca: 0 Erros: 5812  Ac

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[4.81777068e-04 2.05243836e-04 9.99778692e-01 1.44018026e-03
 5.59643338e-05 9.56075509e-05 1.04496284e-02 4.64205001e-06
 2.74780012e-03 2.30497663e-06]
Linha: 58000 Epoca: 0 Erros: 5840  Acerto: 89.93103448275862 %
_________
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1.54327265e-03 4.60081871e-04 9.99721391e-01 2.46412355e-03
 1.62835926e-04 2.97091057e-04 4.85525816e-03 5.18081079e-06
 2.30077305e-03 3.00331760e-06]
Linha: 58020 Epoca: 0 Erros: 5840  Acerto: 89.93450534298518 %
_________
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[4.20826237e-02 9.16467296e-06 2.57207078e-05 7.53238305e-04
 2.14219787e-05 9.94142570e-01 7.44963426e-05 1.97802958e-04
 2.40105974e-03 7.34586547e-04]
Linha: 58040 Epoca: 0 Erros: 5841  Acerto: 89.93625086147485 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[7.93131373e-05 2.79567307e-05 1.08101479e-04 1.27614879e-02
 1.14462539e-02 6.55906703e-04 1.22275230e-03 4.39138587e-03
 5.19481579e-03 9.82773064e-01]
Linha: 58060 Epoca: 0 Erros: 5842  Ac

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1.26692344e-04 1.69023196e-05 3.19838383e-05 8.62750466e-04
 2.89437083e-02 6.24596053e-03 1.74715567e-04 1.27366988e-02
 7.94701395e-03 8.85339724e-01]
Linha: 58640 Epoca: 0 Erros: 5859  Acerto: 90.00852660300137 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.79462290e-01 1.79439095e-07 1.97744207e-03 2.37666414e-03
 1.94430734e-04 2.09364300e-02 1.79459570e-03 2.76592812e-03
 4.20773172e-03 8.57440630e-03]
Linha: 58660 Epoca: 0 Erros: 5861  Acerto: 90.00852369587453 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.59458366e-03 3.81203781e-03 1.88119672e-02 1.72357946e-03
 9.76889983e-05 1.94384404e-02 2.44611510e-04 4.37584402e-05
 9.89339185e-01 5.51892985e-04]
Linha: 58680 Epoca: 0 Erros: 5862  Acerto: 90.01022494887526 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[2.29535604e-04 1.71962713e-05 9.48863905e-05 9.38904331e-05
 1.27166555e-02 1.94670111e-03 5.47257908e-04 2.11859492e-02
 4.73791065e-03 9.40763172e-01]
Linha: 58700 Epoca: 0 Erros: 5862  Ac

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1.92204995e-04 5.71105611e-06 9.28660645e-04 3.25990727e-04
 3.81003524e-05 1.58755622e-03 1.28836421e-05 9.84858352e-01
 7.08858040e-04 1.31845872e-02]
Linha: 59280 Epoca: 0 Erros: 5874  Acerto: 90.0910931174089 %
_________
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[6.78510029e-04 9.53201508e-05 8.17824886e-05 9.74667513e-01
 6.55539613e-05 3.23600672e-03 9.94447795e-07 1.74419625e-02
 5.23246428e-03 1.24817251e-01]
Linha: 59300 Epoca: 0 Erros: 5877  Acerto: 90.0893760539629 %
_________
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.87206707e-01 6.75673882e-07 4.85333251e-04 2.85156898e-04
 3.49747351e-05 1.49642191e-02 8.13177446e-04 2.95138338e-04
 1.13949706e-04 2.62148761e-05]
Linha: 59320 Epoca: 0 Erros: 5880  Acerto: 90.08766014834794 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.20981027e-04 6.89962272e-01 3.13761442e-06 3.10847866e-02
 3.13408980e-03 9.86949969e-02 8.53654880e-05 1.01992299e-03
 2.86518974e-01 1.27709588e-03]
Linha: 59340 Epoca: 0 Erros: 5880  Acer

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.57959989e-04 4.76147137e-01 1.12227703e-02 3.06271722e-02
 7.85541590e-03 1.15581224e-02 5.54739786e-06 9.95276243e-05
 7.21467072e-02 1.29303062e-03]
Linha: 59920 Epoca: 0 Erros: 5908  Acerto: 90.14018691588785 %
_________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[3.01892958e-03 3.01046716e-06 1.37082923e-04 3.36717449e-04
 2.95497841e-03 2.49056488e-02 1.79437494e-04 1.11243525e-01
 1.54171864e-04 5.78494004e-01]
Linha: 59940 Epoca: 0 Erros: 5910  Acerto: 90.14014014014015 %
_________
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.75803671e-03 1.57765492e-05 6.43893629e-03 6.18302457e-06
 1.97196845e-02 6.92708102e-05 9.92872751e-01 9.38529779e-06
 5.63748099e-04 3.20542933e-03]
Linha: 59960 Epoca: 0 Erros: 5911  Acerto: 90.14176117411608 %
_________
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.00223467e-06 9.93415529e-01 3.60229226e-03 9.78594093e-03
 5.23994943e-03 2.68043448e-03 1.21259814e-04 3.90626872e-03
 3.07352507e-03 1.02718970e-03]
Linha: 59980 Epoca: 0 Erros: 5911  Ac